//<auto-generated />


namespace KFLibrary.Win.WinForm.DevEx.Controls
{
    public class MaDoiTuongBhyt
    {
        public int Id { get; set; }
        public int Nhom { get; set; }
        public string Ma { get; set; }
        public int MucHuong { get; set; }
        public string DienGiai { get; set; }
        public string DienGiaiMucHuong { get; set; }
    }
}
