//<auto-generated />

namespace KFLibrary.Win.WinForm.DevEx.Controls
{
    partial class SoTheBhyt
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            DevExpress.Utils.SuperToolTip superToolTip1 = new DevExpress.Utils.SuperToolTip();
            DevExpress.Utils.ToolTipTitleItem toolTipTitleItem1 = new DevExpress.Utils.ToolTipTitleItem();
            DevExpress.Utils.ToolTipItem toolTipItem1 = new DevExpress.Utils.ToolTipItem();
            DevExpress.Utils.SerializableAppearanceObject serializableAppearanceObject1 = new DevExpress.Utils.SerializableAppearanceObject();
            DevExpress.Utils.SuperToolTip superToolTip2 = new DevExpress.Utils.SuperToolTip();
            DevExpress.Utils.ToolTipTitleItem toolTipTitleItem2 = new DevExpress.Utils.ToolTipTitleItem();
            DevExpress.Utils.ToolTipItem toolTipItem2 = new DevExpress.Utils.ToolTipItem();
            DevExpress.Utils.SuperToolTip superToolTip3 = new DevExpress.Utils.SuperToolTip();
            DevExpress.Utils.ToolTipTitleItem toolTipTitleItem3 = new DevExpress.Utils.ToolTipTitleItem();
            DevExpress.Utils.ToolTipItem toolTipItem3 = new DevExpress.Utils.ToolTipItem();
            DevExpress.Utils.SuperToolTip superToolTip4 = new DevExpress.Utils.SuperToolTip();
            DevExpress.Utils.ToolTipTitleItem toolTipTitleItem4 = new DevExpress.Utils.ToolTipTitleItem();
            DevExpress.Utils.ToolTipItem toolTipItem4 = new DevExpress.Utils.ToolTipItem();
            DevExpress.Utils.SuperToolTip superToolTip5 = new DevExpress.Utils.SuperToolTip();
            DevExpress.Utils.ToolTipTitleItem toolTipTitleItem5 = new DevExpress.Utils.ToolTipTitleItem();
            DevExpress.Utils.ToolTipItem toolTipItem5 = new DevExpress.Utils.ToolTipItem();
            DevExpress.Utils.SuperToolTip superToolTip6 = new DevExpress.Utils.SuperToolTip();
            DevExpress.Utils.ToolTipTitleItem toolTipTitleItem6 = new DevExpress.Utils.ToolTipTitleItem();
            DevExpress.Utils.ToolTipItem toolTipItem6 = new DevExpress.Utils.ToolTipItem();
            this.layoutControl1 = new DevExpress.XtraLayout.LayoutControl();
            this.txtMaNoiDangKy = new DevExpress.XtraEditors.TextEdit();
            this.txtMaTinh = new DevExpress.XtraEditors.TextEdit();
            this.txtReadOnlyNoiDangKy = new DevExpress.XtraEditors.TextEdit();
            this.txtReadOnly = new DevExpress.XtraEditors.TextEdit();
            this.txt02 = new DevExpress.XtraEditors.TextEdit();
            this.glkp01 = new DevExpress.XtraEditors.GridLookUpEdit();
            this.repositoryItemMemoEdit1 = new DevExpress.XtraEditors.Repository.RepositoryItemMemoEdit();
            this.gridLookUpEdit1View = new DevExpress.XtraGrid.Views.Grid.GridView();
            this.colMa = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colDienGiai = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colMucHuong = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colNhom = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colDienGiaiMucHuong = new DevExpress.XtraGrid.Columns.GridColumn();
            this.colId = new DevExpress.XtraGrid.Columns.GridColumn();
            this.txt06 = new DevExpress.XtraEditors.TextEdit();
            this.txt04 = new DevExpress.XtraEditors.TextEdit();
            this.txt03 = new DevExpress.XtraEditors.TextEdit();
            this.txt05 = new DevExpress.XtraEditors.TextEdit();
            this.lcgReadOnly = new DevExpress.XtraLayout.LayoutControlGroup();
            this.lciReadOnly = new DevExpress.XtraLayout.LayoutControlItem();
            this.lcgReadOnlyMaNoiDangKyKCB = new DevExpress.XtraLayout.LayoutControlGroup();
            this.lciReadOnlyMaNoiDangKyKCB = new DevExpress.XtraLayout.LayoutControlItem();
            this.lcgEditableMaNoiDangKyKCB = new DevExpress.XtraLayout.LayoutControlGroup();
            this.layoutControlItem5 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem7 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlGroup1 = new DevExpress.XtraLayout.LayoutControlGroup();
            this.lcgEditable = new DevExpress.XtraLayout.LayoutControlGroup();
            this.layoutControlItem8 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem6 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem1 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem2 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem3 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem4 = new DevExpress.XtraLayout.LayoutControlItem();
            this.dxErrorProvider1 = new DevExpress.XtraEditors.DXErrorProvider.DXErrorProvider(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.layoutControl1)).BeginInit();
            this.layoutControl1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.txtMaNoiDangKy.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtMaTinh.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtReadOnlyNoiDangKy.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtReadOnly.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt02.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.glkp01.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.repositoryItemMemoEdit1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridLookUpEdit1View)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt06.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt04.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt03.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt05.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.lcgReadOnly)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.lciReadOnly)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.lcgReadOnlyMaNoiDangKyKCB)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.lciReadOnlyMaNoiDangKyKCB)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.lcgEditableMaNoiDangKyKCB)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem7)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.lcgEditable)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem8)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem6)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dxErrorProvider1)).BeginInit();
            this.SuspendLayout();
            // 
            // layoutControl1
            // 
            this.layoutControl1.AllowCustomizationMenu = false;
            this.layoutControl1.Controls.Add(this.txtMaNoiDangKy);
            this.layoutControl1.Controls.Add(this.txtMaTinh);
            this.layoutControl1.Controls.Add(this.txtReadOnlyNoiDangKy);
            this.layoutControl1.Controls.Add(this.txtReadOnly);
            this.layoutControl1.Controls.Add(this.txt02);
            this.layoutControl1.Controls.Add(this.glkp01);
            this.layoutControl1.Controls.Add(this.txt06);
            this.layoutControl1.Controls.Add(this.txt04);
            this.layoutControl1.Controls.Add(this.txt03);
            this.layoutControl1.Controls.Add(this.txt05);
            this.layoutControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.layoutControl1.HiddenItems.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.lcgReadOnly,
            this.lcgEditableMaNoiDangKyKCB});
            this.layoutControl1.Location = new System.Drawing.Point(0, 0);
            this.layoutControl1.MinimumSize = new System.Drawing.Size(0, 28);
            this.layoutControl1.Name = "layoutControl1";
            this.layoutControl1.OptionsCustomizationForm.DesignTimeCustomizationFormPositionAndSize = new System.Drawing.Rectangle(621, 259, 250, 524);
            this.layoutControl1.OptionsFocus.AllowFocusReadonlyEditors = false;
            this.layoutControl1.Root = this.layoutControlGroup1;
            this.layoutControl1.Size = new System.Drawing.Size(215, 28);
            this.layoutControl1.TabIndex = 0;
            this.layoutControl1.Text = "layoutControl1";
            // 
            // txtMaNoiDangKy
            // 
            this.txtMaNoiDangKy.EditValue = "";
            this.txtMaNoiDangKy.EnterMoveNextControl = true;
            this.txtMaNoiDangKy.Location = new System.Drawing.Point(30, 22);
            this.txtMaNoiDangKy.Name = "txtMaNoiDangKy";
            this.txtMaNoiDangKy.Properties.Appearance.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Bold);
            this.txtMaNoiDangKy.Properties.Appearance.Options.UseFont = true;
            this.txtMaNoiDangKy.Properties.Appearance.Options.UseTextOptions = true;
            this.txtMaNoiDangKy.Properties.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
            this.txtMaNoiDangKy.Properties.Mask.EditMask = "\\d+";
            this.txtMaNoiDangKy.Properties.Mask.MaskType = DevExpress.XtraEditors.Mask.MaskType.RegEx;
            this.txtMaNoiDangKy.Properties.MaxLength = 3;
            this.txtMaNoiDangKy.Size = new System.Drawing.Size(185, 22);
            this.txtMaNoiDangKy.StyleController = this.layoutControl1;
            this.txtMaNoiDangKy.TabIndex = 9;
            // 
            // txtMaTinh
            // 
            this.txtMaTinh.EditValue = "";
            this.txtMaTinh.EnterMoveNextControl = true;
            this.txtMaTinh.Location = new System.Drawing.Point(2, 22);
            this.txtMaTinh.Name = "txtMaTinh";
            this.txtMaTinh.Properties.Appearance.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Bold);
            this.txtMaTinh.Properties.Appearance.Options.UseFont = true;
            this.txtMaTinh.Properties.Appearance.Options.UseTextOptions = true;
            this.txtMaTinh.Properties.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
            this.txtMaTinh.Properties.Mask.EditMask = "\\d+";
            this.txtMaTinh.Properties.Mask.MaskType = DevExpress.XtraEditors.Mask.MaskType.RegEx;
            this.txtMaTinh.Properties.MaxLength = 2;
            this.txtMaTinh.Size = new System.Drawing.Size(26, 22);
            this.txtMaTinh.StyleController = this.layoutControl1;
            this.txtMaTinh.TabIndex = 8;
            // 
            // txtReadOnlyNoiDangKy
            // 
            this.txtReadOnlyNoiDangKy.EditValue = "";
            this.txtReadOnlyNoiDangKy.EnterMoveNextControl = true;
            this.txtReadOnlyNoiDangKy.Location = new System.Drawing.Point(163, 22);
            this.txtReadOnlyNoiDangKy.Name = "txtReadOnlyNoiDangKy";
            this.txtReadOnlyNoiDangKy.Properties.Appearance.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Bold);
            this.txtReadOnlyNoiDangKy.Properties.Appearance.Options.UseFont = true;
            this.txtReadOnlyNoiDangKy.Properties.Appearance.Options.UseTextOptions = true;
            this.txtReadOnlyNoiDangKy.Properties.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
            this.txtReadOnlyNoiDangKy.Properties.MaxLength = 6;
            this.txtReadOnlyNoiDangKy.Properties.ReadOnly = true;
            this.txtReadOnlyNoiDangKy.Size = new System.Drawing.Size(52, 22);
            this.txtReadOnlyNoiDangKy.StyleController = this.layoutControl1;
            this.txtReadOnlyNoiDangKy.TabIndex = 7;
            // 
            // txtReadOnly
            // 
            this.txtReadOnly.EditValue = "";
            this.txtReadOnly.EnterMoveNextControl = true;
            this.txtReadOnly.Location = new System.Drawing.Point(0, 22);
            this.txtReadOnly.Name = "txtReadOnly";
            this.txtReadOnly.Properties.Appearance.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Bold);
            this.txtReadOnly.Properties.Appearance.Options.UseFont = true;
            this.txtReadOnly.Properties.Appearance.Options.UseTextOptions = true;
            this.txtReadOnly.Properties.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
            this.txtReadOnly.Properties.ReadOnly = true;
            this.txtReadOnly.Size = new System.Drawing.Size(161, 22);
            this.txtReadOnly.StyleController = this.layoutControl1;
            this.txtReadOnly.TabIndex = 6;
            // 
            // txt02
            // 
            this.txt02.EditValue = "";
            this.txt02.EnterMoveNextControl = true;
            this.txt02.Location = new System.Drawing.Point(48, 0);
            this.txt02.Name = "txt02";
            this.txt02.Properties.AllowFocused = false;
            this.txt02.Properties.Appearance.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txt02.Properties.Appearance.Options.UseFont = true;
            this.txt02.Properties.Appearance.Options.UseTextOptions = true;
            this.txt02.Properties.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
            this.txt02.Properties.Mask.EditMask = "\\d+";
            this.txt02.Properties.Mask.MaskType = DevExpress.XtraEditors.Mask.MaskType.RegEx;
            this.txt02.Properties.MaxLength = 1;
            this.txt02.Properties.NullValuePrompt = "_";
            this.txt02.Properties.NullValuePromptShowForEmptyValue = true;
            this.txt02.Properties.ReadOnly = true;
            this.txt02.Size = new System.Drawing.Size(18, 22);
            this.txt02.StyleController = this.layoutControl1;
            toolTipTitleItem1.Text = "Nhắc nhở";
            toolTipItem1.LeftIndent = 6;
            toolTipItem1.Text = "Nhập mức hưởng BHYT theo quy định.";
            superToolTip1.Items.Add(toolTipTitleItem1);
            superToolTip1.Items.Add(toolTipItem1);
            this.txt02.SuperTip = superToolTip1;
            this.txt02.TabIndex = 1;
            this.txt02.TextChanged += new System.EventHandler(this.txtO2_TextChanged);
            this.txt02.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txtO2_KeyDown);
            // 
            // glkp01
            // 
            this.glkp01.EditValue = "";
            this.glkp01.EnterMoveNextControl = true;
            this.glkp01.Location = new System.Drawing.Point(0, 0);
            this.glkp01.Name = "glkp01";
            this.glkp01.Properties.AllowNullInput = DevExpress.Utils.DefaultBoolean.True;
            this.glkp01.Properties.Appearance.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Bold);
            this.glkp01.Properties.Appearance.Options.UseFont = true;
            this.glkp01.Properties.Appearance.Options.UseTextOptions = true;
            this.glkp01.Properties.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
            this.glkp01.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo, "", -1, true, false, false, DevExpress.XtraEditors.ImageLocation.MiddleCenter, null, new DevExpress.Utils.KeyShortcut(System.Windows.Forms.Keys.None), serializableAppearanceObject1, "", null, null, true)});
            this.glkp01.Properties.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
            this.glkp01.Properties.DisplayMember = "Ma";
            this.glkp01.Properties.ImmediatePopup = true;
            this.glkp01.Properties.MaxLength = 2;
            this.glkp01.Properties.NullText = "";
            this.glkp01.Properties.PopupFormMinSize = new System.Drawing.Size(205, 0);
            this.glkp01.Properties.PopupFormSize = new System.Drawing.Size(205, 0);
            this.glkp01.Properties.RepositoryItems.AddRange(new DevExpress.XtraEditors.Repository.RepositoryItem[] {
            this.repositoryItemMemoEdit1});
            this.glkp01.Properties.TextEditStyle = DevExpress.XtraEditors.Controls.TextEditStyles.Standard;
            this.glkp01.Properties.ValueMember = "Id";
            this.glkp01.Properties.View = this.gridLookUpEdit1View;
            this.glkp01.Size = new System.Drawing.Size(46, 22);
            this.glkp01.StyleController = this.layoutControl1;
            toolTipTitleItem2.Text = "Nhắc nhở";
            toolTipItem2.LeftIndent = 6;
            toolTipItem2.Text = "Nhập hoặc chọn mã đối tượng tham gia BHYT.";
            superToolTip2.Items.Add(toolTipTitleItem2);
            superToolTip2.Items.Add(toolTipItem2);
            this.glkp01.SuperTip = superToolTip2;
            this.glkp01.TabIndex = 0;
            this.glkp01.EditValueChanged += new System.EventHandler(this.glkp01_EditValueChanged);
            this.glkp01.TextChanged += new System.EventHandler(this.glkp01_TextChanged);
            this.glkp01.KeyDown += new System.Windows.Forms.KeyEventHandler(this.glkp01_KeyDown);
            this.glkp01.PreviewKeyDown += new System.Windows.Forms.PreviewKeyDownEventHandler(this.glkp01_PreviewKeyDown);
            // 
            // repositoryItemMemoEdit1
            // 
            this.repositoryItemMemoEdit1.Name = "repositoryItemMemoEdit1";
            // 
            // gridLookUpEdit1View
            // 
            this.gridLookUpEdit1View.Columns.AddRange(new DevExpress.XtraGrid.Columns.GridColumn[] {
            this.colMa,
            this.colDienGiai,
            this.colMucHuong,
            this.colNhom,
            this.colDienGiaiMucHuong,
            this.colId});
            this.gridLookUpEdit1View.FocusRectStyle = DevExpress.XtraGrid.Views.Grid.DrawFocusRectStyle.RowFocus;
            this.gridLookUpEdit1View.GroupCount = 1;
            this.gridLookUpEdit1View.Name = "gridLookUpEdit1View";
            this.gridLookUpEdit1View.OptionsBehavior.AutoExpandAllGroups = true;
            this.gridLookUpEdit1View.OptionsCustomization.AllowFilter = false;
            this.gridLookUpEdit1View.OptionsSelection.EnableAppearanceFocusedCell = false;
            this.gridLookUpEdit1View.OptionsView.RowAutoHeight = true;
            this.gridLookUpEdit1View.OptionsView.ShowFilterPanelMode = DevExpress.XtraGrid.Views.Base.ShowFilterPanelMode.Never;
            this.gridLookUpEdit1View.OptionsView.ShowGroupPanel = false;
            this.gridLookUpEdit1View.RowHeight = 3;
            this.gridLookUpEdit1View.SortInfo.AddRange(new DevExpress.XtraGrid.Columns.GridColumnSortInfo[] {
            new DevExpress.XtraGrid.Columns.GridColumnSortInfo(this.colNhom, DevExpress.Data.ColumnSortOrder.Ascending)});
            // 
            // colMa
            // 
            this.colMa.AppearanceCell.Options.UseTextOptions = true;
            this.colMa.AppearanceCell.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
            this.colMa.AppearanceHeader.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold);
            this.colMa.AppearanceHeader.Options.UseFont = true;
            this.colMa.AppearanceHeader.Options.UseTextOptions = true;
            this.colMa.AppearanceHeader.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
            this.colMa.AppearanceHeader.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            this.colMa.Caption = "Mã";
            this.colMa.FieldName = "Ma";
            this.colMa.MaxWidth = 36;
            this.colMa.MinWidth = 36;
            this.colMa.Name = "colMa";
            this.colMa.OptionsColumn.FixedWidth = true;
            this.colMa.Visible = true;
            this.colMa.VisibleIndex = 0;
            this.colMa.Width = 36;
            // 
            // colDienGiai
            // 
            this.colDienGiai.AppearanceHeader.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold);
            this.colDienGiai.AppearanceHeader.Options.UseFont = true;
            this.colDienGiai.AppearanceHeader.Options.UseTextOptions = true;
            this.colDienGiai.AppearanceHeader.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
            this.colDienGiai.AppearanceHeader.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            this.colDienGiai.Caption = "Diễn giải";
            this.colDienGiai.ColumnEdit = this.repositoryItemMemoEdit1;
            this.colDienGiai.FieldName = "DienGiai";
            this.colDienGiai.Name = "colDienGiai";
            this.colDienGiai.Visible = true;
            this.colDienGiai.VisibleIndex = 2;
            this.colDienGiai.Width = 915;
            // 
            // colMucHuong
            // 
            this.colMucHuong.AppearanceCell.Options.UseTextOptions = true;
            this.colMucHuong.AppearanceCell.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
            this.colMucHuong.AppearanceHeader.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold);
            this.colMucHuong.AppearanceHeader.Options.UseFont = true;
            this.colMucHuong.AppearanceHeader.Options.UseTextOptions = true;
            this.colMucHuong.AppearanceHeader.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
            this.colMucHuong.AppearanceHeader.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            this.colMucHuong.Caption = "Mức hưởng";
            this.colMucHuong.FieldName = "MucHuong";
            this.colMucHuong.Name = "colMucHuong";
            this.colMucHuong.Visible = true;
            this.colMucHuong.VisibleIndex = 1;
            this.colMucHuong.Width = 122;
            // 
            // colNhom
            // 
            this.colNhom.AppearanceHeader.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold);
            this.colNhom.AppearanceHeader.Options.UseFont = true;
            this.colNhom.AppearanceHeader.Options.UseTextOptions = true;
            this.colNhom.AppearanceHeader.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
            this.colNhom.AppearanceHeader.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            this.colNhom.Caption = "Nhóm";
            this.colNhom.FieldName = "Nhom";
            this.colNhom.Name = "colNhom";
            this.colNhom.Visible = true;
            this.colNhom.VisibleIndex = 4;
            // 
            // colDienGiaiMucHuong
            // 
            this.colDienGiaiMucHuong.AppearanceHeader.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold);
            this.colDienGiaiMucHuong.AppearanceHeader.Options.UseFont = true;
            this.colDienGiaiMucHuong.AppearanceHeader.Options.UseTextOptions = true;
            this.colDienGiaiMucHuong.AppearanceHeader.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
            this.colDienGiaiMucHuong.AppearanceHeader.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            this.colDienGiaiMucHuong.Caption = "Diễn giải mức hưởng";
            this.colDienGiaiMucHuong.ColumnEdit = this.repositoryItemMemoEdit1;
            this.colDienGiaiMucHuong.FieldName = "DienGiaiMucHuong";
            this.colDienGiaiMucHuong.Name = "colDienGiaiMucHuong";
            // 
            // colId
            // 
            this.colId.AppearanceHeader.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Bold);
            this.colId.AppearanceHeader.Options.UseFont = true;
            this.colId.AppearanceHeader.Options.UseTextOptions = true;
            this.colId.AppearanceHeader.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
            this.colId.AppearanceHeader.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            this.colId.Caption = "Id";
            this.colId.FieldName = "Id";
            this.colId.Name = "colId";
            // 
            // txt06
            // 
            this.txt06.EditValue = "";
            this.txt06.EnterMoveNextControl = true;
            this.txt06.Location = new System.Drawing.Point(159, 0);
            this.txt06.Name = "txt06";
            this.txt06.Properties.Appearance.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Bold);
            this.txt06.Properties.Appearance.Options.UseFont = true;
            this.txt06.Properties.Appearance.Options.UseTextOptions = true;
            this.txt06.Properties.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
            this.txt06.Properties.Mask.EditMask = "\\d+";
            this.txt06.Properties.Mask.MaskType = DevExpress.XtraEditors.Mask.MaskType.RegEx;
            this.txt06.Properties.MaxLength = 5;
            this.txt06.Properties.NullValuePrompt = "_____";
            this.txt06.Properties.NullValuePromptShowForEmptyValue = true;
            this.txt06.Size = new System.Drawing.Size(56, 22);
            this.txt06.StyleController = this.layoutControl1;
            toolTipTitleItem3.Text = "Nhắc nhở";
            toolTipItem3.LeftIndent = 6;
            toolTipItem3.Text = "Nhập số thứ tự của người tham gia BHYT trong 01 đơn vị.";
            superToolTip3.Items.Add(toolTipTitleItem3);
            superToolTip3.Items.Add(toolTipItem3);
            this.txt06.SuperTip = superToolTip3;
            this.txt06.TabIndex = 5;
            this.txt06.TextChanged += new System.EventHandler(this.txtO6_TextChanged);
            this.txt06.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txtO6_KeyDown);
            this.txt06.PreviewKeyDown += new System.Windows.Forms.PreviewKeyDownEventHandler(this.PreviewKeyDown);
            // 
            // txt04
            // 
            this.txt04.EditValue = "";
            this.txt04.EnterMoveNextControl = true;
            this.txt04.Location = new System.Drawing.Point(96, 0);
            this.txt04.Name = "txt04";
            this.txt04.Properties.Appearance.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Bold);
            this.txt04.Properties.Appearance.Options.UseFont = true;
            this.txt04.Properties.Appearance.Options.UseTextOptions = true;
            this.txt04.Properties.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
            this.txt04.Properties.Mask.EditMask = "\\d+";
            this.txt04.Properties.Mask.MaskType = DevExpress.XtraEditors.Mask.MaskType.RegEx;
            this.txt04.Properties.MaxLength = 2;
            this.txt04.Properties.NullValuePrompt = "__";
            this.txt04.Properties.NullValuePromptShowForEmptyValue = true;
            this.txt04.Size = new System.Drawing.Size(26, 22);
            this.txt04.StyleController = this.layoutControl1;
            toolTipTitleItem4.Text = "Nhắc nhở";
            toolTipItem4.LeftIndent = 6;
            toolTipItem4.Text = "Nhập mã quận, huyện, thị xã, thành phố trực thuộc tỉnh, nơi quản lý đầu mối của n" +
    "gười tham gia BHYT.";
            superToolTip4.Items.Add(toolTipTitleItem4);
            superToolTip4.Items.Add(toolTipItem4);
            this.txt04.SuperTip = superToolTip4;
            this.txt04.TabIndex = 3;
            this.txt04.TextChanged += new System.EventHandler(this.txtO4_TextChanged);
            this.txt04.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txtO4_KeyDown);
            // 
            // txt03
            // 
            this.txt03.EditValue = "";
            this.txt03.EnterMoveNextControl = true;
            this.txt03.Location = new System.Drawing.Point(68, 0);
            this.txt03.Name = "txt03";
            this.txt03.Properties.Appearance.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txt03.Properties.Appearance.Options.UseFont = true;
            this.txt03.Properties.Appearance.Options.UseTextOptions = true;
            this.txt03.Properties.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
            this.txt03.Properties.Mask.EditMask = "\\d+";
            this.txt03.Properties.Mask.MaskType = DevExpress.XtraEditors.Mask.MaskType.RegEx;
            this.txt03.Properties.MaxLength = 2;
            this.txt03.Properties.NullValuePrompt = "__";
            this.txt03.Properties.NullValuePromptShowForEmptyValue = true;
            this.txt03.Size = new System.Drawing.Size(26, 22);
            this.txt03.StyleController = this.layoutControl1;
            toolTipTitleItem5.Text = "Nhắc nhở";
            toolTipItem5.LeftIndent = 6;
            toolTipItem5.Text = "Nhập mã tỉnh, thành phố trực thuộc Trung ương, nơi phát hành thẻ BHYT.";
            superToolTip5.Items.Add(toolTipTitleItem5);
            superToolTip5.Items.Add(toolTipItem5);
            this.txt03.SuperTip = superToolTip5;
            this.txt03.TabIndex = 2;
            this.txt03.TextChanged += new System.EventHandler(this.txtO3_TextChanged);
            this.txt03.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txtO3_KeyDown);
            // 
            // txt05
            // 
            this.txt05.EditValue = "";
            this.txt05.EnterMoveNextControl = true;
            this.txt05.Location = new System.Drawing.Point(124, 0);
            this.txt05.Name = "txt05";
            this.txt05.Properties.Appearance.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Bold);
            this.txt05.Properties.Appearance.Options.UseFont = true;
            this.txt05.Properties.Appearance.Options.UseTextOptions = true;
            this.txt05.Properties.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
            this.txt05.Properties.Mask.EditMask = "\\d+";
            this.txt05.Properties.Mask.MaskType = DevExpress.XtraEditors.Mask.MaskType.RegEx;
            this.txt05.Properties.MaxLength = 3;
            this.txt05.Properties.NullValuePrompt = "___";
            this.txt05.Properties.NullValuePromptShowForEmptyValue = true;
            this.txt05.Size = new System.Drawing.Size(33, 22);
            this.txt05.StyleController = this.layoutControl1;
            toolTipTitleItem6.Text = "Nhắc nhở";
            toolTipItem6.LeftIndent = 6;
            toolTipItem6.Text = "Nhập mã đơn vị quản lý, theo địa giới hành chính và theo loại đối tượng.";
            superToolTip6.Items.Add(toolTipTitleItem6);
            superToolTip6.Items.Add(toolTipItem6);
            this.txt05.SuperTip = superToolTip6;
            this.txt05.TabIndex = 4;
            this.txt05.TextChanged += new System.EventHandler(this.txtO5_TextChanged);
            this.txt05.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txtO5_KeyDown);
            // 
            // lcgReadOnly
            // 
            this.lcgReadOnly.CustomizationFormText = "lcgReadOnly";
            this.lcgReadOnly.GroupBordersVisible = false;
            this.lcgReadOnly.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.lciReadOnly,
            this.lcgReadOnlyMaNoiDangKyKCB});
            this.lcgReadOnly.Location = new System.Drawing.Point(0, 22);
            this.lcgReadOnly.Name = "lcgReadOnly";
            this.lcgReadOnly.Size = new System.Drawing.Size(215, 22);
            this.lcgReadOnly.Text = "lcgReadOnly";
            // 
            // lciReadOnly
            // 
            this.lciReadOnly.Control = this.txtReadOnly;
            this.lciReadOnly.CustomizationFormText = "lciReadOnly";
            this.lciReadOnly.Location = new System.Drawing.Point(0, 0);
            this.lciReadOnly.MaxSize = new System.Drawing.Size(163, 0);
            this.lciReadOnly.MinSize = new System.Drawing.Size(163, 22);
            this.lciReadOnly.Name = "lciReadOnly";
            this.lciReadOnly.Padding = new DevExpress.XtraLayout.Utils.Padding(0, 2, 0, 0);
            this.lciReadOnly.Size = new System.Drawing.Size(163, 22);
            this.lciReadOnly.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.lciReadOnly.Text = "lciReadOnly";
            this.lciReadOnly.TextSize = new System.Drawing.Size(0, 0);
            this.lciReadOnly.TextToControlDistance = 0;
            this.lciReadOnly.TextVisible = false;
            // 
            // lcgReadOnlyMaNoiDangKyKCB
            // 
            this.lcgReadOnlyMaNoiDangKyKCB.CustomizationFormText = "lcgMaNoiDangKyKCB";
            this.lcgReadOnlyMaNoiDangKyKCB.GroupBordersVisible = false;
            this.lcgReadOnlyMaNoiDangKyKCB.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.lciReadOnlyMaNoiDangKyKCB});
            this.lcgReadOnlyMaNoiDangKyKCB.Location = new System.Drawing.Point(163, 0);
            this.lcgReadOnlyMaNoiDangKyKCB.Name = "lcgReadOnlyMaNoiDangKyKCB";
            this.lcgReadOnlyMaNoiDangKyKCB.Size = new System.Drawing.Size(52, 22);
            this.lcgReadOnlyMaNoiDangKyKCB.Text = "lcgReadOnlyMaNoiDangKyKCB";
            // 
            // lciReadOnlyMaNoiDangKyKCB
            // 
            this.lciReadOnlyMaNoiDangKyKCB.Control = this.txtReadOnlyNoiDangKy;
            this.lciReadOnlyMaNoiDangKyKCB.CustomizationFormText = "lciMaNoiDangKyKCB";
            this.lciReadOnlyMaNoiDangKyKCB.Location = new System.Drawing.Point(0, 0);
            this.lciReadOnlyMaNoiDangKyKCB.MaxSize = new System.Drawing.Size(52, 0);
            this.lciReadOnlyMaNoiDangKyKCB.MinSize = new System.Drawing.Size(52, 22);
            this.lciReadOnlyMaNoiDangKyKCB.Name = "lciReadOnlyMaNoiDangKyKCB";
            this.lciReadOnlyMaNoiDangKyKCB.Padding = new DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 0);
            this.lciReadOnlyMaNoiDangKyKCB.Size = new System.Drawing.Size(52, 22);
            this.lciReadOnlyMaNoiDangKyKCB.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.lciReadOnlyMaNoiDangKyKCB.Text = "lciReadOnlyMaNoiDangKyKCB";
            this.lciReadOnlyMaNoiDangKyKCB.TextSize = new System.Drawing.Size(0, 0);
            this.lciReadOnlyMaNoiDangKyKCB.TextToControlDistance = 0;
            this.lciReadOnlyMaNoiDangKyKCB.TextVisible = false;
            // 
            // lcgEditableMaNoiDangKyKCB
            // 
            this.lcgEditableMaNoiDangKyKCB.CustomizationFormText = "lcgEditableMaNoiDangKyKCB";
            this.lcgEditableMaNoiDangKyKCB.GroupBordersVisible = false;
            this.lcgEditableMaNoiDangKyKCB.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.layoutControlItem5,
            this.layoutControlItem7});
            this.lcgEditableMaNoiDangKyKCB.Location = new System.Drawing.Point(0, 22);
            this.lcgEditableMaNoiDangKyKCB.Name = "lcgEditableMaNoiDangKyKCB";
            this.lcgEditableMaNoiDangKyKCB.Size = new System.Drawing.Size(215, 470);
            this.lcgEditableMaNoiDangKyKCB.Text = "lcgEditableMaNoiDangKyKCB";
            // 
            // layoutControlItem5
            // 
            this.layoutControlItem5.Control = this.txtMaTinh;
            this.layoutControlItem5.CustomizationFormText = "lciMaTinh";
            this.layoutControlItem5.Location = new System.Drawing.Point(0, 0);
            this.layoutControlItem5.MinSize = new System.Drawing.Size(28, 22);
            this.layoutControlItem5.Name = "layoutControlItem5";
            this.layoutControlItem5.Padding = new DevExpress.XtraLayout.Utils.Padding(2, 0, 0, 0);
            this.layoutControlItem5.Size = new System.Drawing.Size(28, 470);
            this.layoutControlItem5.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.layoutControlItem5.Text = "lciMaTinh";
            this.layoutControlItem5.TextSize = new System.Drawing.Size(0, 0);
            this.layoutControlItem5.TextToControlDistance = 0;
            this.layoutControlItem5.TextVisible = false;
            // 
            // layoutControlItem7
            // 
            this.layoutControlItem7.Control = this.txtMaNoiDangKy;
            this.layoutControlItem7.CustomizationFormText = "lciNoiDangKy";
            this.layoutControlItem7.Location = new System.Drawing.Point(28, 0);
            this.layoutControlItem7.MinSize = new System.Drawing.Size(35, 22);
            this.layoutControlItem7.Name = "layoutControlItem7";
            this.layoutControlItem7.Padding = new DevExpress.XtraLayout.Utils.Padding(2, 0, 0, 0);
            this.layoutControlItem7.Size = new System.Drawing.Size(187, 470);
            this.layoutControlItem7.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.layoutControlItem7.Text = "lciNoiDangKy";
            this.layoutControlItem7.TextSize = new System.Drawing.Size(0, 0);
            this.layoutControlItem7.TextToControlDistance = 0;
            this.layoutControlItem7.TextVisible = false;
            // 
            // layoutControlGroup1
            // 
            this.layoutControlGroup1.CustomizationFormText = "Root";
            this.layoutControlGroup1.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True;
            this.layoutControlGroup1.GroupBordersVisible = false;
            this.layoutControlGroup1.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.lcgEditable});
            this.layoutControlGroup1.Location = new System.Drawing.Point(0, 0);
            this.layoutControlGroup1.Name = "Root";
            this.layoutControlGroup1.Padding = new DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 0);
            this.layoutControlGroup1.Size = new System.Drawing.Size(215, 28);
            this.layoutControlGroup1.Text = "Root";
            this.layoutControlGroup1.TextVisible = false;
            // 
            // lcgEditable
            // 
            this.lcgEditable.CustomizationFormText = "lcgEditable";
            this.lcgEditable.GroupBordersVisible = false;
            this.lcgEditable.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.layoutControlItem8,
            this.layoutControlItem6,
            this.layoutControlItem1,
            this.layoutControlItem2,
            this.layoutControlItem3,
            this.layoutControlItem4});
            this.lcgEditable.Location = new System.Drawing.Point(0, 0);
            this.lcgEditable.Name = "lcgEditable";
            this.lcgEditable.Size = new System.Drawing.Size(215, 28);
            this.lcgEditable.Text = "lcgEditable";
            // 
            // layoutControlItem8
            // 
            this.layoutControlItem8.Control = this.glkp01;
            this.layoutControlItem8.CustomizationFormText = "Ô 1";
            this.layoutControlItem8.Location = new System.Drawing.Point(0, 0);
            this.layoutControlItem8.MaxSize = new System.Drawing.Size(48, 22);
            this.layoutControlItem8.MinSize = new System.Drawing.Size(48, 22);
            this.layoutControlItem8.Name = "layoutControlItem8";
            this.layoutControlItem8.Padding = new DevExpress.XtraLayout.Utils.Padding(0, 2, 0, 0);
            this.layoutControlItem8.Size = new System.Drawing.Size(48, 28);
            this.layoutControlItem8.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.layoutControlItem8.Text = "Ô 1";
            this.layoutControlItem8.TextSize = new System.Drawing.Size(0, 0);
            this.layoutControlItem8.TextToControlDistance = 0;
            this.layoutControlItem8.TextVisible = false;
            // 
            // layoutControlItem6
            // 
            this.layoutControlItem6.Control = this.txt02;
            this.layoutControlItem6.CustomizationFormText = "Ô 2";
            this.layoutControlItem6.Location = new System.Drawing.Point(48, 0);
            this.layoutControlItem6.MaxSize = new System.Drawing.Size(20, 22);
            this.layoutControlItem6.MinSize = new System.Drawing.Size(20, 22);
            this.layoutControlItem6.Name = "layoutControlItem6";
            this.layoutControlItem6.Padding = new DevExpress.XtraLayout.Utils.Padding(0, 2, 0, 0);
            this.layoutControlItem6.Size = new System.Drawing.Size(20, 28);
            this.layoutControlItem6.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.layoutControlItem6.Text = "Ô 2";
            this.layoutControlItem6.TextSize = new System.Drawing.Size(0, 0);
            this.layoutControlItem6.TextToControlDistance = 0;
            this.layoutControlItem6.TextVisible = false;
            // 
            // layoutControlItem1
            // 
            this.layoutControlItem1.Control = this.txt03;
            this.layoutControlItem1.CustomizationFormText = "Ô 3";
            this.layoutControlItem1.Location = new System.Drawing.Point(68, 0);
            this.layoutControlItem1.MaxSize = new System.Drawing.Size(28, 22);
            this.layoutControlItem1.MinSize = new System.Drawing.Size(28, 22);
            this.layoutControlItem1.Name = "layoutControlItem1";
            this.layoutControlItem1.Padding = new DevExpress.XtraLayout.Utils.Padding(0, 2, 0, 0);
            this.layoutControlItem1.Size = new System.Drawing.Size(28, 28);
            this.layoutControlItem1.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.layoutControlItem1.Text = "Ô 3";
            this.layoutControlItem1.TextSize = new System.Drawing.Size(0, 0);
            this.layoutControlItem1.TextToControlDistance = 0;
            this.layoutControlItem1.TextVisible = false;
            // 
            // layoutControlItem2
            // 
            this.layoutControlItem2.Control = this.txt04;
            this.layoutControlItem2.CustomizationFormText = "Ô 4";
            this.layoutControlItem2.Location = new System.Drawing.Point(96, 0);
            this.layoutControlItem2.MaxSize = new System.Drawing.Size(28, 22);
            this.layoutControlItem2.MinSize = new System.Drawing.Size(28, 22);
            this.layoutControlItem2.Name = "layoutControlItem2";
            this.layoutControlItem2.Padding = new DevExpress.XtraLayout.Utils.Padding(0, 2, 0, 0);
            this.layoutControlItem2.Size = new System.Drawing.Size(28, 28);
            this.layoutControlItem2.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.layoutControlItem2.Text = "Ô 4";
            this.layoutControlItem2.TextSize = new System.Drawing.Size(0, 0);
            this.layoutControlItem2.TextToControlDistance = 0;
            this.layoutControlItem2.TextVisible = false;
            // 
            // layoutControlItem3
            // 
            this.layoutControlItem3.Control = this.txt05;
            this.layoutControlItem3.ControlAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.layoutControlItem3.CustomizationFormText = "Ô 5";
            this.layoutControlItem3.Location = new System.Drawing.Point(124, 0);
            this.layoutControlItem3.MaxSize = new System.Drawing.Size(35, 22);
            this.layoutControlItem3.MinSize = new System.Drawing.Size(35, 22);
            this.layoutControlItem3.Name = "layoutControlItem3";
            this.layoutControlItem3.Padding = new DevExpress.XtraLayout.Utils.Padding(0, 2, 0, 0);
            this.layoutControlItem3.Size = new System.Drawing.Size(35, 28);
            this.layoutControlItem3.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.layoutControlItem3.Text = "Ô 5";
            this.layoutControlItem3.TextSize = new System.Drawing.Size(0, 0);
            this.layoutControlItem3.TextToControlDistance = 0;
            this.layoutControlItem3.TextVisible = false;
            // 
            // layoutControlItem4
            // 
            this.layoutControlItem4.Control = this.txt06;
            this.layoutControlItem4.CustomizationFormText = "Ô 6";
            this.layoutControlItem4.Location = new System.Drawing.Point(159, 0);
            this.layoutControlItem4.MaxSize = new System.Drawing.Size(56, 22);
            this.layoutControlItem4.MinSize = new System.Drawing.Size(56, 22);
            this.layoutControlItem4.Name = "layoutControlItem4";
            this.layoutControlItem4.Padding = new DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 0);
            this.layoutControlItem4.Size = new System.Drawing.Size(56, 28);
            this.layoutControlItem4.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.layoutControlItem4.Text = "Ô 6";
            this.layoutControlItem4.TextSize = new System.Drawing.Size(0, 0);
            this.layoutControlItem4.TextToControlDistance = 0;
            this.layoutControlItem4.TextVisible = false;
            // 
            // dxErrorProvider1
            // 
            this.dxErrorProvider1.ContainerControl = this;
            // 
            // SoTheBhyt
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.layoutControl1);
            this.Margin = new System.Windows.Forms.Padding(0);
            this.MinimumSize = new System.Drawing.Size(215, 22);
            this.Name = "SoTheBhyt";
            this.Size = new System.Drawing.Size(215, 22);
            this.Load += new System.EventHandler(this.SoTheBHYT_Load);
            ((System.ComponentModel.ISupportInitialize)(this.layoutControl1)).EndInit();
            this.layoutControl1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.txtMaNoiDangKy.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtMaTinh.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtReadOnlyNoiDangKy.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtReadOnly.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt02.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.glkp01.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.repositoryItemMemoEdit1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridLookUpEdit1View)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt06.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt04.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt03.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt05.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.lcgReadOnly)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.lciReadOnly)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.lcgReadOnlyMaNoiDangKyKCB)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.lciReadOnlyMaNoiDangKyKCB)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.lcgEditableMaNoiDangKyKCB)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem7)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.lcgEditable)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem8)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem6)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dxErrorProvider1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private DevExpress.XtraLayout.LayoutControl layoutControl1;
        private DevExpress.XtraLayout.LayoutControlGroup layoutControlGroup1;
        private DevExpress.XtraEditors.TextEdit txt05;
        private DevExpress.XtraEditors.TextEdit txt04;
        private DevExpress.XtraEditors.TextEdit txt03;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem1;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem2;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem3;
        private DevExpress.XtraEditors.GridLookUpEdit glkp01;
        private DevExpress.XtraGrid.Views.Grid.GridView gridLookUpEdit1View;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem8;
        private DevExpress.XtraEditors.TextEdit txt02;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem6;
        private DevExpress.XtraEditors.Repository.RepositoryItemMemoEdit repositoryItemMemoEdit1;
        private DevExpress.XtraGrid.Columns.GridColumn colNhom;
        private DevExpress.XtraGrid.Columns.GridColumn colMa;
        private DevExpress.XtraGrid.Columns.GridColumn colDienGiai;
        private DevExpress.XtraGrid.Columns.GridColumn colMucHuong;
        private DevExpress.XtraGrid.Columns.GridColumn colDienGiaiMucHuong;
        private DevExpress.XtraEditors.DXErrorProvider.DXErrorProvider dxErrorProvider1;
        private DevExpress.XtraEditors.TextEdit txtReadOnly;
        private DevExpress.XtraLayout.LayoutControlItem lciReadOnly;
        private DevExpress.XtraLayout.LayoutControlGroup lcgEditable;
        private DevExpress.XtraLayout.LayoutControlGroup lcgReadOnly;
        private DevExpress.XtraEditors.TextEdit txtReadOnlyNoiDangKy;
        private DevExpress.XtraLayout.LayoutControlGroup lcgReadOnlyMaNoiDangKyKCB;
        private DevExpress.XtraLayout.LayoutControlItem lciReadOnlyMaNoiDangKyKCB;
        private DevExpress.XtraEditors.TextEdit txtMaNoiDangKy;
        private DevExpress.XtraEditors.TextEdit txtMaTinh;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem5;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem7;
        private DevExpress.XtraLayout.LayoutControlGroup lcgEditableMaNoiDangKyKCB;
        private DevExpress.XtraEditors.TextEdit txt06;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem4;
        private DevExpress.XtraGrid.Columns.GridColumn colId;
    }
}
