//<auto-generated />

using System.ComponentModel;
using System.ComponentModel.Design;

namespace KFLibrary.Win.WinForm.DevEx.Controls
{
    internal class SoTheBhytDesignerActionList : DesignerActionList
    {
        /* -------------------------------- Enums ------------------------------------ */
        /* --------------------------------------------------------------------------- */

        /* ------------------------------- Variables --------------------------------- */
        private SoTheBhyt _component;
        private DesignerActionUIService _designerActionUISvc = null;
        /* --------------------------------------------------------------------------- */

        /* ------------------------------ Properties --------------------------------- */
        //public string FullText
        //{
        //    get
        //    {
        //        return _component.FullText;
        //    }
        //    set
        //    {
        //        Utils.GetPropertyByName(_component, "FullText").SetValue(_component, value);
        //    }
        //}

        /* --------------------------------------------------------------------------- */

        /* -------------------------------- Methods ---------------------------------- */
        public SoTheBhytDesignerActionList(IComponent component)
            : base(component)
        {
            _component = component as SoTheBhyt;

            _designerActionUISvc =
                this.GetService(typeof(DesignerActionUIService))
                    as DesignerActionUIService;
        }

        public override DesignerActionItemCollection GetSortedActionItems()
        {
            DesignerActionItemCollection items = new DesignerActionItemCollection();

            // Items
            items.Add(new DesignerActionHeaderItem("Thông tin"));
            items.Add(new DesignerActionPropertyItem("FullText", "Fulltext",
                "Thông tin", "Giá trị fulltext"));


            return items;
        }
        /* --------------------------------------------------------------------------- */

        /* --------------------------- Event handlers--------------------------------- */
        /* --------------------------------------------------------------------------- */

        /* --------------------------------- Test ------------------------------------ */
        // Method test code
        private void Test()
        {
            // Todo: test code here
        }
        /* --------------------------------------------------------------------------- */
    }
}
