//<auto-generated />


namespace KFLibrary.Win.WinForm.DevEx.Controls
{
    public partial class MessageControl : DevExpress.XtraEditors.XtraForm
    {
        public MessageControl()
        {
            InitializeComponent();
        }
    }
}
