//<auto-generated />

namespace KFLibrary.Win.WinForm.DevEx.Controls
{
    partial class ThongTinBenhNhanNoiTru
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.layoutControl1 = new DevExpress.XtraLayout.LayoutControl();
            this.ucMaBenhNhan = new KFLibrary.Win.WinForm.DevEx.Controls.MaBenhNhan();
            this.spinNamSinh = new DevExpress.XtraEditors.SpinEdit();
            this.chkLaNu = new DevExpress.XtraEditors.CheckEdit();
            this.txtGiuong = new DevExpress.XtraEditors.TextEdit();
            this.txtPhong = new DevExpress.XtraEditors.TextEdit();
            this.txtHoTenBenhNhan = new DevExpress.XtraEditors.TextEdit();
            this.lueDoiTuong = new DevExpress.XtraEditors.LookUpEdit();
            this.layoutControlGroup1 = new DevExpress.XtraLayout.LayoutControlGroup();
            this.layoutControlItem1 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem3 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem5 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem4 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem7 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem6 = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlItem2 = new DevExpress.XtraLayout.LayoutControlItem();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControl1)).BeginInit();
            this.layoutControl1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.spinNamSinh.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.chkLaNu.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtGiuong.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtPhong.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtHoTenBenhNhan.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.lueDoiTuong.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem7)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem6)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem2)).BeginInit();
            this.SuspendLayout();
            // 
            // layoutControl1
            // 
            this.layoutControl1.AllowCustomizationMenu = false;
            this.layoutControl1.Controls.Add(this.ucMaBenhNhan);
            this.layoutControl1.Controls.Add(this.spinNamSinh);
            this.layoutControl1.Controls.Add(this.chkLaNu);
            this.layoutControl1.Controls.Add(this.txtGiuong);
            this.layoutControl1.Controls.Add(this.txtPhong);
            this.layoutControl1.Controls.Add(this.txtHoTenBenhNhan);
            this.layoutControl1.Controls.Add(this.lueDoiTuong);
            this.layoutControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.layoutControl1.Location = new System.Drawing.Point(0, 0);
            this.layoutControl1.Name = "layoutControl1";
            this.layoutControl1.OptionsCustomizationForm.DesignTimeCustomizationFormPositionAndSize = new System.Drawing.Rectangle(421, 318, 250, 350);
            this.layoutControl1.OptionsFocus.AllowFocusReadonlyEditors = false;
            this.layoutControl1.Root = this.layoutControlGroup1;
            this.layoutControl1.Size = new System.Drawing.Size(580, 50);
            this.layoutControl1.TabIndex = 0;
            this.layoutControl1.Text = "layoutControl1";
            // 
            // ucMaBenhNhan
            // 
            this.ucMaBenhNhan.Location = new System.Drawing.Point(73, 2);
            this.ucMaBenhNhan.Margin = new System.Windows.Forms.Padding(0);
            this.ucMaBenhNhan.MinimumSize = new System.Drawing.Size(132, 22);
            this.ucMaBenhNhan.Name = "ucMaBenhNhan";
            this.ucMaBenhNhan.PasswordChar = '\0';
            this.ucMaBenhNhan.Size = new System.Drawing.Size(133, 22);
            this.ucMaBenhNhan.SplitChar = '-';
            this.ucMaBenhNhan.TabIndex = 27;
            // 
            // spinNamSinh
            // 
            this.spinNamSinh.EditValue = new decimal(new int[] {
            1900,
            0,
            0,
            0});
            this.spinNamSinh.Location = new System.Drawing.Point(501, 2);
            this.spinNamSinh.Name = "spinNamSinh";
            this.spinNamSinh.Properties.AllowNullInput = DevExpress.Utils.DefaultBoolean.True;
            this.spinNamSinh.Properties.DisplayFormat.FormatString = "d";
            this.spinNamSinh.Properties.DisplayFormat.FormatType = DevExpress.Utils.FormatType.Numeric;
            this.spinNamSinh.Properties.EditFormat.FormatString = "d";
            this.spinNamSinh.Properties.EditFormat.FormatType = DevExpress.Utils.FormatType.Numeric;
            this.spinNamSinh.Properties.IsFloatValue = false;
            this.spinNamSinh.Properties.Mask.EditMask = "d";
            this.spinNamSinh.Properties.MaxLength = 4;
            this.spinNamSinh.Properties.MaxValue = new decimal(new int[] {
            9999,
            0,
            0,
            0});
            this.spinNamSinh.Properties.MinValue = new decimal(new int[] {
            1900,
            0,
            0,
            0});
            this.spinNamSinh.Size = new System.Drawing.Size(36, 20);
            this.spinNamSinh.StyleController = this.layoutControl1;
            this.spinNamSinh.TabIndex = 26;
            // 
            // chkLaNu
            // 
            this.chkLaNu.Location = new System.Drawing.Point(541, 2);
            this.chkLaNu.Name = "chkLaNu";
            this.chkLaNu.Properties.Caption = "Nữ";
            this.chkLaNu.Size = new System.Drawing.Size(37, 19);
            this.chkLaNu.StyleController = this.layoutControl1;
            this.chkLaNu.TabIndex = 25;
            // 
            // txtGiuong
            // 
            this.txtGiuong.EditValue = "";
            this.txtGiuong.Location = new System.Drawing.Point(501, 28);
            this.txtGiuong.Name = "txtGiuong";
            this.txtGiuong.Size = new System.Drawing.Size(77, 20);
            this.txtGiuong.StyleController = this.layoutControl1;
            this.txtGiuong.TabIndex = 22;
            // 
            // txtPhong
            // 
            this.txtPhong.EditValue = "";
            this.txtPhong.Location = new System.Drawing.Point(247, 28);
            this.txtPhong.Name = "txtPhong";
            this.txtPhong.Size = new System.Drawing.Size(202, 20);
            this.txtPhong.StyleController = this.layoutControl1;
            this.txtPhong.TabIndex = 22;
            // 
            // txtHoTenBenhNhan
            // 
            this.txtHoTenBenhNhan.EditValue = "";
            this.txtHoTenBenhNhan.Location = new System.Drawing.Point(247, 2);
            this.txtHoTenBenhNhan.Name = "txtHoTenBenhNhan";
            this.txtHoTenBenhNhan.Size = new System.Drawing.Size(202, 20);
            this.txtHoTenBenhNhan.StyleController = this.layoutControl1;
            this.txtHoTenBenhNhan.TabIndex = 22;
            // 
            // lueDoiTuong
            // 
            this.lueDoiTuong.Location = new System.Drawing.Point(73, 28);
            this.lueDoiTuong.Name = "lueDoiTuong";
            this.lueDoiTuong.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.lueDoiTuong.Properties.Columns.AddRange(new DevExpress.XtraEditors.Controls.LookUpColumnInfo[] {
            new DevExpress.XtraEditors.Controls.LookUpColumnInfo("Id", "Id", 20, DevExpress.Utils.FormatType.None, "", false, DevExpress.Utils.HorzAlignment.Default),
            new DevExpress.XtraEditors.Controls.LookUpColumnInfo("Ma", "Mã"),
            new DevExpress.XtraEditors.Controls.LookUpColumnInfo("Ten", "Tên")});
            this.lueDoiTuong.Properties.DisplayMember = "Ten";
            this.lueDoiTuong.Properties.NullText = "";
            this.lueDoiTuong.Properties.ValueMember = "Id";
            this.lueDoiTuong.Size = new System.Drawing.Size(133, 20);
            this.lueDoiTuong.StyleController = this.layoutControl1;
            this.lueDoiTuong.TabIndex = 24;
            // 
            // layoutControlGroup1
            // 
            this.layoutControlGroup1.CustomizationFormText = "layoutControlGroup1";
            this.layoutControlGroup1.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True;
            this.layoutControlGroup1.GroupBordersVisible = false;
            this.layoutControlGroup1.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.layoutControlItem1,
            this.layoutControlItem3,
            this.layoutControlItem5,
            this.layoutControlItem4,
            this.layoutControlItem7,
            this.layoutControlItem6,
            this.layoutControlItem2});
            this.layoutControlGroup1.Location = new System.Drawing.Point(0, 0);
            this.layoutControlGroup1.Name = "Root";
            this.layoutControlGroup1.Padding = new DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 0);
            this.layoutControlGroup1.Size = new System.Drawing.Size(580, 50);
            this.layoutControlGroup1.Text = "Root";
            this.layoutControlGroup1.TextVisible = false;
            // 
            // layoutControlItem1
            // 
            this.layoutControlItem1.Control = this.txtHoTenBenhNhan;
            this.layoutControlItem1.CustomizationFormText = "Họ tên";
            this.layoutControlItem1.Location = new System.Drawing.Point(208, 0);
            this.layoutControlItem1.Name = "layoutControlItem1";
            this.layoutControlItem1.Size = new System.Drawing.Size(243, 26);
            this.layoutControlItem1.Text = "Họ tên";
            this.layoutControlItem1.TextAlignMode = DevExpress.XtraLayout.TextAlignModeItem.AutoSize;
            this.layoutControlItem1.TextSize = new System.Drawing.Size(32, 13);
            this.layoutControlItem1.TextToControlDistance = 5;
            // 
            // layoutControlItem3
            // 
            this.layoutControlItem3.Control = this.ucMaBenhNhan;
            this.layoutControlItem3.CustomizationFormText = "Mã bệnh nhân";
            this.layoutControlItem3.Location = new System.Drawing.Point(0, 0);
            this.layoutControlItem3.MaxSize = new System.Drawing.Size(208, 26);
            this.layoutControlItem3.MinSize = new System.Drawing.Size(208, 26);
            this.layoutControlItem3.Name = "layoutControlItem3";
            this.layoutControlItem3.Size = new System.Drawing.Size(208, 26);
            this.layoutControlItem3.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.layoutControlItem3.Text = "Mã bệnh nhân";
            this.layoutControlItem3.TextSize = new System.Drawing.Size(68, 13);
            // 
            // layoutControlItem5
            // 
            this.layoutControlItem5.Control = this.spinNamSinh;
            this.layoutControlItem5.CustomizationFormText = "Năm sinh";
            this.layoutControlItem5.Location = new System.Drawing.Point(451, 0);
            this.layoutControlItem5.MinSize = new System.Drawing.Size(82, 24);
            this.layoutControlItem5.Name = "layoutControlItem5";
            this.layoutControlItem5.Size = new System.Drawing.Size(88, 26);
            this.layoutControlItem5.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.layoutControlItem5.Text = "Năm sinh";
            this.layoutControlItem5.TextAlignMode = DevExpress.XtraLayout.TextAlignModeItem.AutoSize;
            this.layoutControlItem5.TextSize = new System.Drawing.Size(43, 13);
            this.layoutControlItem5.TextToControlDistance = 5;
            // 
            // layoutControlItem4
            // 
            this.layoutControlItem4.Control = this.chkLaNu;
            this.layoutControlItem4.CustomizationFormText = "Là nữ";
            this.layoutControlItem4.Location = new System.Drawing.Point(539, 0);
            this.layoutControlItem4.MaxSize = new System.Drawing.Size(41, 26);
            this.layoutControlItem4.MinSize = new System.Drawing.Size(41, 26);
            this.layoutControlItem4.Name = "layoutControlItem4";
            this.layoutControlItem4.Size = new System.Drawing.Size(41, 26);
            this.layoutControlItem4.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.layoutControlItem4.Text = "Là nữ";
            this.layoutControlItem4.TextSize = new System.Drawing.Size(0, 0);
            this.layoutControlItem4.TextToControlDistance = 0;
            this.layoutControlItem4.TextVisible = false;
            // 
            // layoutControlItem7
            // 
            this.layoutControlItem7.Control = this.txtGiuong;
            this.layoutControlItem7.CustomizationFormText = "Giường";
            this.layoutControlItem7.Location = new System.Drawing.Point(451, 26);
            this.layoutControlItem7.MaxSize = new System.Drawing.Size(129, 24);
            this.layoutControlItem7.MinSize = new System.Drawing.Size(129, 24);
            this.layoutControlItem7.Name = "layoutControlItem7";
            this.layoutControlItem7.Size = new System.Drawing.Size(129, 24);
            this.layoutControlItem7.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.layoutControlItem7.Text = "Giường";
            this.layoutControlItem7.TextAlignMode = DevExpress.XtraLayout.TextAlignModeItem.CustomSize;
            this.layoutControlItem7.TextSize = new System.Drawing.Size(43, 20);
            this.layoutControlItem7.TextToControlDistance = 5;
            // 
            // layoutControlItem6
            // 
            this.layoutControlItem6.Control = this.txtPhong;
            this.layoutControlItem6.CustomizationFormText = "Buồng";
            this.layoutControlItem6.Location = new System.Drawing.Point(208, 26);
            this.layoutControlItem6.Name = "layoutControlItem6";
            this.layoutControlItem6.Size = new System.Drawing.Size(243, 24);
            this.layoutControlItem6.Text = "Phòng";
            this.layoutControlItem6.TextAlignMode = DevExpress.XtraLayout.TextAlignModeItem.CustomSize;
            this.layoutControlItem6.TextSize = new System.Drawing.Size(32, 20);
            this.layoutControlItem6.TextToControlDistance = 5;
            // 
            // layoutControlItem2
            // 
            this.layoutControlItem2.Control = this.lueDoiTuong;
            this.layoutControlItem2.CustomizationFormText = "Đối tượng";
            this.layoutControlItem2.Location = new System.Drawing.Point(0, 26);
            this.layoutControlItem2.MaxSize = new System.Drawing.Size(208, 24);
            this.layoutControlItem2.MinSize = new System.Drawing.Size(208, 24);
            this.layoutControlItem2.Name = "layoutControlItem2";
            this.layoutControlItem2.Size = new System.Drawing.Size(208, 24);
            this.layoutControlItem2.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.layoutControlItem2.Text = "Đối tượng";
            this.layoutControlItem2.TextSize = new System.Drawing.Size(68, 13);
            // 
            // ThongTinBenhNhanNoiTru
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.layoutControl1);
            this.MinimumSize = new System.Drawing.Size(0, 50);
            this.Name = "ThongTinBenhNhanNoiTru";
            this.Size = new System.Drawing.Size(580, 50);
            ((System.ComponentModel.ISupportInitialize)(this.layoutControl1)).EndInit();
            this.layoutControl1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.spinNamSinh.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.chkLaNu.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtGiuong.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtPhong.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtHoTenBenhNhan.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.lueDoiTuong.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem7)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem6)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem2)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private DevExpress.XtraLayout.LayoutControl layoutControl1;
        private DevExpress.XtraLayout.LayoutControlGroup layoutControlGroup1;
        private DevExpress.XtraEditors.SpinEdit spinNamSinh;
        private DevExpress.XtraEditors.CheckEdit chkLaNu;
        private DevExpress.XtraEditors.TextEdit txtHoTenBenhNhan;
        private DevExpress.XtraEditors.LookUpEdit lueDoiTuong;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem1;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem2;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem4;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem5;
        private MaBenhNhan ucMaBenhNhan;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem3;
        private DevExpress.XtraEditors.TextEdit txtGiuong;
        private DevExpress.XtraEditors.TextEdit txtPhong;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem7;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem6;
    }
}
