//<auto-generated />

using System;

namespace KFLibrary.Win.WinForm.DevEx.Controls
{
    public partial class ThongTinBenhNhanNoiTru : DevExpress.XtraEditors.XtraUserControl
    {
        /* -------------------------------- Enums ------------------------------------ */
        #region "Enums"

        #endregion
        /* --------------------------------------------------------------------------- */

        /* --------------------------------- Events ---------------------------------- */
        #region "Events"

        #endregion
        /* --------------------------------------------------------------------------- */

        /* ------------------------------- Variables --------------------------------- */
        #region "Variables"
        private Int64 _idChuyenKhoa;
        #endregion
        /* --------------------------------------------------------------------------- */

        /* ------------------------------ Properties --------------------------------- */
        #region "Properties"
        public object DatasourceDoiTuong
        {
            get
            {
                return lueDoiTuong.Properties.DataSource;
            }
            set
            {
                lueDoiTuong.Properties.DataSource = value;
            }
        }

        public string MaBenhNhan
        {
            get
            {
                return ucMaBenhNhan.FullText;
            }
        }

        public string HoTen
        {
            get
            {
                return txtHoTenBenhNhan.Text;
            }
        }

        public int NamSinh
        {
            get
            {
                return Convert.ToInt32(spinNamSinh.Value);
            }
        }

        public bool LaNu
        {
            get
            {
                return chkLaNu.Checked;
            }
        }

        public int IdDoiTuong
        {
            get
            {
                return Convert.ToInt32(lueDoiTuong.EditValue);
            }
        }

        public string Phong
        {
            get
            {
                return txtPhong.Text;
            }
        }

        public string Giuong
        {
            get
            {
                return txtGiuong.Text;
            }
        }
        #endregion
        /* --------------------------------------------------------------------------- */

        /* -------------------------------- Methods ---------------------------------- */
        #region "Methods"
        public ThongTinBenhNhanNoiTru()
        {
            InitializeComponent();
        }
        #endregion
        /* --------------------------------------------------------------------------- */

        /* --------------------------- Event handlers--------------------------------- */
        #region "Event handlers"

        #endregion
        /* --------------------------------------------------------------------------- */

        /* ------------------------------ Sub classes -------------------------------- */
        #region "Sub classes"

        #endregion
        /* --------------------------------------------------------------------------- */

        /* --------------------------------- Test ------------------------------------ */
        #region "Tests"
        // Method test code
        private void Test()
        {
            // Todo: test code here
        }
        #endregion
        /* --------------------------------------------------------------------------- */
    }
}
