//<auto-generated />

using System.Drawing;
using System.Windows.Forms;
using DevExpress.XtraEditors;

namespace KFLibrary.Win.WinForm.DevEx.Controls
{
    public partial class AboutControl : DevExpress.XtraEditors.XtraUserControl
    {
        /* -------------------------------- Enums ------------------------------------ */
        #region "Enums"

        #endregion
        /* --------------------------------------------------------------------------- */

        /* --------------------------------- Events ---------------------------------- */
        #region "Events"

        #endregion
        /* --------------------------------------------------------------------------- */

        /* ------------------------------- Variables --------------------------------- */
        #region "Variables"
        private XtraForm _ownerForm = null;
        #endregion
        /* --------------------------------------------------------------------------- */

        /* ------------------------------ Properties --------------------------------- */
        #region "Properties"
        private XtraForm OwnerForm
        {
            get
            {
                // Lazy initialize
                if (_ownerForm == null)
                {
                    _ownerForm = new XtraForm();
                }
                return _ownerForm;
            }
        }

        public AboutControlInfo DefaultInfo
        {
            get;
            set;
        }
        #endregion
        /* --------------------------------------------------------------------------- */

        /* -------------------------------- Methods ---------------------------------- */
        #region "Methods"
        public AboutControl()
        {
            InitializeComponent();           
        }

        public AboutControl(AboutControlInfo aboutControlInfo)
        {
            InitializeComponent(); 

            // Set default value
            SetDefault(aboutControlInfo);
        }

        public void SetDefault(AboutControlInfo aboutControlInfo)
        {
            this.OwnerForm.Text = aboutControlInfo.FormInfo.Title;

            AboutControlInfo info = new AboutControlInfo()
            {
                FormInfo = new AboutControlInfo.OwnerFormInfo()
                {
                    Title = "dasdasdsa",
                    StartPosition = FormStartPosition.CenterScreen
                }
            };



            this.OwnerForm.StartPosition = FormStartPosition.CenterScreen;
            this.OwnerForm.Size = new Size(640, 480);
        }

        public void Show()
        {
            
        }

        public void ShowDialog()
        {
            if (this.OwnerForm == null)
            {
                return;
            }

            this.Dock = DockStyle.Fill;
            this.OwnerForm.Controls.Add(this);
            this.OwnerForm.ShowDialog();
        }
        #endregion
        /* --------------------------------------------------------------------------- */

        /* --------------------------- Event handlers--------------------------------- */
        #region "Event handlers"

        #endregion
        /* --------------------------------------------------------------------------- */

        /* ------------------------------ Sub classes -------------------------------- */
        #region "Sub classes"

        #endregion
        /* --------------------------------------------------------------------------- */

        /* --------------------------------- Test ------------------------------------ */
        #region "Tests"
        // Method test code
        private void Test()
        {
            // Todo: test code here
        }
        #endregion
        /* --------------------------------------------------------------------------- */
    }
}
