//<auto-generated />

using System.Collections.Generic;
using System.Drawing;
using System.Windows.Forms;
using DevExpress.XtraEditors;

namespace KFLibrary.Win.WinForm.DevEx.Controls
{
    public class AboutControlInfo
    {
        public OwnerFormInfo FormInfo { get; set; }

        //public virtual EditorButtonCollection Buttons { get; }
        public List<SimpleButton> Buttons { get; set; }



        public class OwnerFormInfo
        {
            public string Title { get; set; }
            public Icon Icon { get; set; }
            public bool IsModal { get; set; }
            public FormStartPosition StartPosition { get; set; }
        }
    }
}
