//<auto-generated />

#region "Author"
/****************************************************************************************
 * Solution     : CUSC His Framework
 * Project code : APP1105
 * Author       : Dương Nguyễn Phú Cường
 * Company      : Cusc Software
 * Version      : 1.0.0.1
 * Created date : 29/03/2013
 ***************************************************************************************/
#endregion

using System;

namespace KFLibrary.Utilities
{
    public class EventArgs<T> : EventArgs
    {
        private T _data;

        public EventArgs(T data)
        {
            _data = data;
        }

        public T IsValid
        {
            get { return _data; }
        }
    }

    //DNPC
    public class EventArgs<T, P> : EventArgs
    {
        private T _data1;
        private P _data2;

        public EventArgs(T data1, P data2)
        {
            _data1 = data1;
            _data2 = data2;
        }

        public T NhanVien
        {
            get { return _data1; }
        }

        public P TextTabSelected
        {
            get { return _data2; }
        }
    }
}
