//<auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Net.Mail;
using System.IO;
using System.Reflection;

namespace KFLibrary.Net.Mail
{
    public static class MailExtension
    {
        /// <summary>
        /// Converts a MailMessage to an EML file stream.
        /// </summary>
        /// <param name="msg"></param>
        /// <returns></returns>
        public static void SaveEML(this MailMessage msg, string filePath)
        {
            using (var client = new SmtpClient())
            {
                var id = Guid.NewGuid();

                var tempFolder = Path.Combine(Path.GetTempPath(), Assembly.GetExecutingAssembly().GetName().Name);
                tempFolder = Path.Combine(tempFolder, "MailMessageToEMLTemp");

                // create a temp folder to hold just this .eml file so that we can find it easily.
                tempFolder = Path.Combine(tempFolder, id.ToString());

                if (!Directory.Exists(tempFolder))
                {
                    Directory.CreateDirectory(tempFolder);
                }

                client.UseDefaultCredentials = true;
                client.DeliveryMethod = SmtpDeliveryMethod.SpecifiedPickupDirectory;
                client.PickupDirectoryLocation = tempFolder;
                client.Send(msg);

                // tempFolder should contain 1 eml file
                //var filePath = Directory.GetFiles(tempFolder).Single();

                // stream out the contents
                //using (var fs = new FileStream(filePath, FileMode.Open))
                //{
                //    fs.CopyTo(str);
                //}

                //using (var fs = new FileStream(filePath, FileMode.Create))
                using(var fs = File.Create(filePath))
                {


                    //myOtherObject.InputStream.CopyTo(fileStream);
                    //fs.Write();

                }
            }
        }
    }
}
