//<auto-generated />

using System.Text;

#pragma warning disable 1591

namespace ExceptionReporting.Mail
{
	/// <summary>
	/// textual content for email
	/// </summary>
	public class EmailTextBuilder
	{
		public string CreateIntro(bool takeScreenshot)
		{
			var s = new StringBuilder()
				.AppendLine("Đây là email gởi tự động.");

			if (takeScreenshot)
			{
				s.AppendLine("Đính kèm file là ảnh chụp màn hình lúc xảy ra sự cố.")
				 .AppendLine();
			}

			return s.ToString();
		}

	    public string CreateFooter()
	    {
            var footerHtml = new StringBuilder();
            footerHtml.Append("<hr></hr>");
	        footerHtml.Append("<span STYLE=\"color: red; font-size: 10px; font-weight: bold\">Đây là email được gởi từ Trung tâm thông báo (CBN) Cusc Biz''s Notification.");
            footerHtml.Append("<br></br>");
            footerHtml.Append("Vui lòng không reply, gởi mail vào địa chỉ này.</span>");
            footerHtml.Append("<hr></hr>");
            footerHtml.Append("<div>");
            footerHtml.Append("<span STYLE=\"color: blue; font-size: 15px; font-weight: bold\">(CBN) Cusc Biz's Notification</span>");
            footerHtml.Append("<br></br>");
            footerHtml.Append("Software Developer - BIZ Group <br></br>");
            footerHtml.Append("Software Department, Can Tho University Software Center (CUSC) <br></br>");
            footerHtml.Append("Phone: +84 710 373 1072 ext. 520 Fax: +84 710 373 1071 ext. 119' <br></br>");
            footerHtml.Append("Website: www.cusc.vn");
            footerHtml.Append("</div>");
	        return footerHtml.ToString();
	    }
	}
}
#pragma warning restore 1591
