//<auto-generated />

using System.ComponentModel;
using System.ComponentModel.Design;
using DevExpress.XtraEditors;

namespace KFLibrary.Win.WinForm.DevEx.Controls
{
    internal class CommonDesignerActionList : DesignerActionList
    {
        /* -------------------------------- Enums ------------------------------------ */
        /* --------------------------------------------------------------------------- */

        /* ------------------------------- Variables --------------------------------- */
        private IComponent _component;
        private DesignerActionUIService _designerAcionUISvc = null;
        /* --------------------------------------------------------------------------- */

        /* ------------------------------ Properties --------------------------------- */
        /* --------------------------------------------------------------------------- */

        /* -------------------------------- Methods ---------------------------------- */
        public CommonDesignerActionList(IComponent component)
            : base(component)
        {
            _component = component;

            _designerAcionUISvc =
                this.GetService(typeof(DesignerActionUIService)) as DesignerActionUIService;
        }

        public override DesignerActionItemCollection GetSortedActionItems()
        {
            DesignerActionItemCollection items = new DesignerActionItemCollection();

            items.Add(new DesignerActionMethodItem(this, "About", "Tác giả", "About",
                "Giới thiệu tác giả và thông tin hỗ trợ.", true));

            return items;
        }

        public void About()
        {
            XtraMessageBox.Show("Cusc Software - BIZ Group", "Thông báo", System.Windows.Forms.MessageBoxButtons.OK,
                 System.Windows.Forms.MessageBoxIcon.Information);
        }
        /* --------------------------------------------------------------------------- */

        /* --------------------------- Event handlers--------------------------------- */
        /* --------------------------------------------------------------------------- */

        /* --------------------------------- Test ------------------------------------ */
        // Method test code
        private void Test()
        {
            // Todo: test code here
        }
        /* --------------------------------------------------------------------------- */
    }
}
