//<auto-generated />


namespace KFLibrary.Win.WinForm.DevEx.Controls
{
    public partial class RibbonForm1 : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        public RibbonForm1()
        {
            InitializeComponent();
        }
    }
}
