//<auto-generated />

using System;
using System.Text.RegularExpressions;
using DevExpress.XtraEditors;

namespace KFLibrary.Win.WinForm.DevEx.Controls
{
    public class Validator
    {

        //[DesignerSerializationVisibility(DesignerSerializationVisibility.Visible)]
        //[DefaultValue("")]
        //[Category("BHYT")]
        //[Description("Ký hiệu bằng số (theo số thứ tự từ 1 đến 9), quy định mức hưởng BHYT")]
        //public string TextO2
        //{
        //    get
        //    {
        //        return txtO2.Text;
        //    }
        //    set
        //    {
        //        string temp = value;

        //        // Clear khoảng trắng
        //        temp = temp.Trim();

        //        if (String.IsNullOrEmpty(temp))
        //        {
        //            txtO2.Text = temp;
        //            return;
        //        }

        //        // Exception chuỗi nhập quá dài
        //        if (temp.Length > txtO2.Properties.MaxLength)
        //        {
        //            throw new ArgumentException(
        //                String.Format("Chuỗi nhập quá dài. Tối đa là {0} ký tự",
        //                    txtO2.Properties.MaxLength));
        //        }

        //        // Exception chuỗi nhập không đúng định dạng
        //        var pattern = txtO2.Properties.Mask.EditMask;
        //        var match = Regex.Match(temp, pattern);
        //        if (!match.Success)
        //        {
        //            throw new ArgumentException(
        //                String.Format("Chuỗi nhập không đúng định dạng. Ký tự được phép nhập : {0}",
        //                    txtO2.Properties.Mask.EditMask));
        //        }

        //        txtO2.Text = temp;
        //    }
        //}

        public static string ConvertStringToValid(string value, TextEdit control)
        {
            string temp = value;

            //// Clear khoảng trắng
            //temp = temp.Trim();

            // Return nếu chuỗi rỗng
            if (String.IsNullOrEmpty(temp))
            {
                return temp;
            }

            // Exception chuỗi nhập quá dài
            if (temp.Length > control.Properties.MaxLength)
            {
                throw new ArgumentException(
                    String.Format("Chuỗi nhập quá dài. Tối đa là {0} ký tự",
                        control.Properties.MaxLength));
            }

            // Exception chuỗi chứa khoảng trắng
            if (temp.Contains(" "))
            {
                throw new ArgumentException(
                    String.Format("Chuỗi nhập không đúng định dạng. Không được chứa khoảng trắng."));
            }

            // Exception chuỗi nhập không đúng định dạng
            var pattern = control.Properties.Mask.EditMask;
            var match = Regex.Match(temp, pattern);

            //Regex das = new Regex()

            if (!match.Success)
            {
                throw new ArgumentException(
                    String.Format("Chuỗi nhập không đúng định dạng. Ký tự được phép nhập : {0}",
                        control.Properties.Mask.EditMask));
            }

            return temp;
        }
    }
}
