//<auto-generated />

#region "Author"
/****************************************************************************************
 * Solution     : CUSC His Framework
 * Project code : APP1105
 * Author       : Dương Nguyễn Phú Cường
 * Company      : Cusc Software
 * Version      : 1.0.0.1
 * Created date : 29/03/2013
 ***************************************************************************************/
#endregion

using System.Drawing;
using System.Windows.Forms;

namespace KFLibrary.Win.WinForm.Utilities
{
    public class FullScreen
    {
        /* -------------------------------- Enums ------------------------------------ */
        #region "Enums"

        #endregion
        /* --------------------------------------------------------------------------- */

        /* --------------------------------- Events ---------------------------------- */
        #region "Events"

        #endregion
        /* --------------------------------------------------------------------------- */

        /* ------------------------------- Variables --------------------------------- */
        #region "Variables"
        private FormWindowState _frmWindowState;
        private FormBorderStyle _frmBorderStyle;
        private bool _topMost;
        private Rectangle _bounds;
        private bool _maximizeBox;
        private bool _minimizeBox;
        #endregion
        /* --------------------------------------------------------------------------- */

        /* ------------------------------ Properties --------------------------------- */
        #region "Properties"
        /// <summary>
        /// Xác định có đang ở chế độ Fullscreen không?
        /// </summary>
        public bool IsFullScreen
        {
            get;
            set;
        }
        #endregion
        /* --------------------------------------------------------------------------- */

        /* -------------------------------- Methods ---------------------------------- */
        #region "Methods"
        /// <summary>
        /// Constructor.
        /// </summary>
        public FullScreen()
        {
            this.IsFullScreen = false;
        }

        /// <summary>
        /// Chuyển form sang chế độ fullscreen.
        /// </summary>
        public void EnterFullScreen(Form targetForm)
        {
            if (!IsFullScreen)
            {
                Save(targetForm);  // Lưu trạng thái form

                //targetForm.WindowState = FormWindowState.Maximized;
                //targetForm.TopMost = true;
                targetForm.FormBorderStyle = FormBorderStyle.None;
                targetForm.MaximizeBox = false;
                targetForm.MinimizeBox = false;
                targetForm.Bounds = Screen.PrimaryScreen.Bounds;
                //Screen.GetBounds(targetForm);

                IsFullScreen = true;
            }
        }

        /// <summary>
        /// Lưu trạng thái hiện tại của form
        /// </summary>
        private void Save(Form targetForm)
        {
            _frmWindowState = targetForm.WindowState;
            _frmBorderStyle = targetForm.FormBorderStyle;
            _topMost = targetForm.TopMost;
            _bounds = targetForm.Bounds;
            _minimizeBox = targetForm.MinimizeBox;
            _maximizeBox = targetForm.MaximizeBox;
        }

        /// <summary>
        /// Leave the full screen mode and restore the original window state.
        /// </summary>
        public void LeaveFullScreen(Form targetForm)
        {
            if (IsFullScreen)
            {
                // Restore the original Window state.
                targetForm.WindowState = _frmWindowState;
                targetForm.FormBorderStyle = _frmBorderStyle;
                targetForm.TopMost = _topMost;
                targetForm.Bounds = _bounds;
                targetForm.MinimizeBox = _minimizeBox;
                targetForm.MaximizeBox = _maximizeBox;

                IsFullScreen = false;
            }
        }
        #endregion
        /* --------------------------------------------------------------------------- */

        /* --------------------------- Event handlers--------------------------------- */
        #region "Event handlers"

        #endregion
        /* --------------------------------------------------------------------------- */

        /* ------------------------------ Sub classes -------------------------------- */
        #region "Sub classes"

        #endregion
        /* --------------------------------------------------------------------------- */

        /* --------------------------------- Test ------------------------------------ */
        #region "Tests"
        // Method test code
        private void Test()
        {
            // Todo: test code here
        }
        #endregion
        /* --------------------------------------------------------------------------- */
    }
}
