//<auto-generated />

#region "Author"
/****************************************************************************************
 * Solution     : CUSC His Framework
 * Project code : APP1105
 * Author       : Dương Nguyễn Phú Cường
 * Company      : Cusc Software
 * Version      : 1.0.0.1
 * Created date : 29/03/2013
 ***************************************************************************************/
#endregion

using System.Drawing;
using System.Windows.Forms;

namespace KFLibrary.Win.WinForm.Utilities
{
    public class WinFormUtilities
    {
        public static void CenterForm(Form theForm)
        {
            theForm.Location = new Point(
                Screen.PrimaryScreen.WorkingArea.Width / 2 - theForm.Width / 2,
                Screen.PrimaryScreen.WorkingArea.Height / 2 - theForm.Height / 2);
        }

        public static void CenterForm(Form theForm, Form parentForm)
        {
            theForm.Location = new Point(
                parentForm.Width / 2 - theForm.Width / 2,
                parentForm.Height / 2 - theForm.Height / 2);
        }
    }
}
