//<auto-generated />

#region "Author"
/****************************************************************************************
 * Solution     : CUSC His Framework
 * Project code : APP1105
 * Author       : Dương Nguyễn Phú Cường
 * Company      : Cusc Software
 * Version      : 1.0.0.1
 * Created date : 29/03/2013
 ***************************************************************************************/
#endregion


using System.Collections.Generic;
using System.Diagnostics;

namespace KFLibrary.Offices
{
    public class WordManager
    {
        /// <summary>
        ///Lưu lại các process Word hiện có, tránh kill nhầm file Word người dùng đang thao tác
        /// </summary>
        /// <returns></returns>
        public static List<int> GetCurrentWordProcessId()
        {
            List<int> lstProcessID = new List<int>();
            foreach (Process process in Process.GetProcessesByName("winword"))
            {
                lstProcessID.Add(process.Id);
            }
            return lstProcessID;
        }

        /// <summary>
        ///Kill process Word xuất lỗi, bỏ qua các process Word đã được lưu trữ
        /// </summary>
        /// <param name="lstProcessID">List Word process ID không cần kill</param>
        public static void SeftKillProcess(List<int> lstProcessID)
        {
            foreach (Process process in Process.GetProcessesByName("winword"))
            {
                if (!process.HasExited && !lstProcessID.Contains(process.Id))
                {
                    process.Kill();
                }
            }
        }
    }
}
