//<auto-generated />

#region "Author"
/****************************************************************************************
 * Solution     : CUSC His Framework
 * Project code : APP1105
 * Author       : Dương Nguyễn Phú Cường
 * Company      : Cusc Software
 * Version      : 1.0.0.1
 * Created date : 29/03/2013
 ***************************************************************************************/
#endregion

using System.Runtime.InteropServices;
using System.Text;

namespace KFLibrary.Files
{
    public class IniWrapper
    {
        #region Variables
        private string _path;
        #endregion

        #region Properties
        public string Path
        {
            get { return _path; }
            set { _path = value; }
        }
        #endregion

        #region Win APIs
        //[DllImport("kernel32.dll")]
        //private static extern int GetPrivateProfileString(
        //    string section,
        //    string key,
        //    string def,
        //    StringBuilder retVal,
        //    int size,
        //    string filePath);

        //[DllImport("kernel32")]
        //private static extern long WritePrivateProfileString(
        //    string section, 
        //    string key, 
        //    string val, 
        //    string filePath);

        [DllImport("kernel32.dll", CharSet = CharSet.Unicode)]
        private static extern int GetPrivateProfileString(
           string lpAppName,
           string lpKeyName,
           string lpDefault,
           StringBuilder lpReturnedString,
           int nSize,
           string lpFileName);

        [DllImport("kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
        [return: MarshalAs(UnmanagedType.Bool)]
        static extern bool WritePrivateProfileString(
            string lpAppName,
            string lpKeyName,
            string lpString,
            string lpFileName);

        #endregion

        #region Methods
        public IniWrapper()
        {
            //this._path = Application.StartupPath + "\\Config\\config.ini";
        }

        public string ReadValue(string Section, string Key)
        {
            StringBuilder temp = new StringBuilder(255);
            int i = GetPrivateProfileString(Section, Key, "", temp, 255, this._path);
            return temp.ToString();
        }

        public void WriteValue(string Section, string Key, string Value)
        {
            WritePrivateProfileString(Section, Key, Value, this._path);
        }

        //public void CreateDefaultConfigFile()
        //{
        //    string sectionName = "Database";
        //    WriteValue(sectionName, "Server", ".\\sql2k5");
        //    WriteValue(sectionName, "Initial catalog", "QLQC");
        //    WriteValue(sectionName, "UID", "sa");
        //    WriteValue(sectionName, "PWD", "123456");

        //    string secOther = "Other";
        //    WriteValue(secOther, "Startup", "false");
        //    WriteValue(secOther, "Topmost", "false");
        //    WriteValue(secOther, "Systemtray", "false");
        //}
        #endregion
    }
}
