//<auto-generated />

#region "Author"
/****************************************************************************************
 * Solution     : CUSC His Framework
 * Project code : APP1105
 * Author       : Dương Nguyễn Phú Cường
 * Company      : Cusc Software
 * Version      : 1.0.0.1
 * Created date : 29/03/2013
 ***************************************************************************************/
#endregion

using System.Linq;
using System.Xml.Linq;

namespace KFLibrary.Files
{
    public class XmlWrapper
    {
        public string FilePath { get; set; }

        public void Load()
        {
            XDocument doc = XDocument.Load(this.FilePath);

            var s = from a in doc.Elements("About")
                    select a;
        }
    }
}
