//<auto-generated />

#region "Author"
/****************************************************************************************
 * Solution     : CUSC His Framework
 * Project code : APP1105
 * Author       : Dương Nguyễn Phú Cường
 * Company      : Cusc Software
 * Version      : 1.0.0.1
 * Created date : 29/03/2013
 ***************************************************************************************/
#endregion

using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.DXErrorProvider;

namespace KFLibrary.Win.WinForm.DevEx.Extensions
{
    public static class XtraErrorProviderExtension
    {
        public static bool Validate(this DXErrorProvider errorProvider,
            bool useThongBaoLoiChung = true,
            string errMsg = "Thông tin nhập không hợp lệ. Vui lòng kiểm tra lại!",
            string errTitle = "Thông báo",
            MessageBoxButtons buttons = MessageBoxButtons.OK,
            MessageBoxIcon icon = MessageBoxIcon.Information)//, ValidationConstraints = ValidationConstraints.Enabled)
        {
            var container = errorProvider.ContainerControl;
            if (container is UserControl)
            {
                var uc = container as UserControl;
                uc.ValidateChildren();
            }
            else if (container is Form)
            {
                var frm = container as Form;
                frm.ValidateChildren();
            }

            // Kiểm tra lỗi
            if (errorProvider.HasErrors)
            {
                //Show thông báo lỗi
                if (useThongBaoLoiChung == true)
                {
                    XtraMessageBox.Show(errMsg, errTitle, buttons, icon);
                }

                // Focus vào control đầu tiên có lỗi
                foreach (var item in errorProvider.GetControlsWithError())
                {
                    if (item.CanFocus)
                    {
                        item.Focus();
                        //Show thông báo lỗi
                        if (useThongBaoLoiChung == false)
                        {
                            XtraMessageBox.Show(errorProvider.GetError(item), errTitle, buttons, icon);
                        }
                        return false;
                    }
                }
            }

            // OK
            return true;
        }
    }
}
