//<auto-generated />

#region "Author"
/****************************************************************************************
 * Solution     : CUSC His Framework
 * Project code : APP1105
 * Author       : Dương Nguyễn Phú Cường
 * Company      : Cusc Software
 * Version      : 1.0.0.1
 * Created date : 29/03/2013
 ***************************************************************************************/
#endregion

using System;
using System.Collections.Generic;

namespace KFLibrary.DataTypes.Extensions
{
    /// <summary>
    /// Contains extension methods for the <see cref="System.Decimal"/> class
    /// </summary>
    public static class DecimalExtension
    {
        #region "Decimal"

        #region Convert numberic to Vietnamese String
        /// <summary>
        /// Hàm chuyển đổi tiền số thành tiền chữ tiếng Việt nam
        /// </summary>
        /// <param name="input">Số tiền cần chuyển đổi</param>
        /// <returns>Chuỗi tiền chữ VN</returns>
        public static String ToMoneyVietnamese(this decimal p_input)
        {
            //input = input.Replace(",", "");
            string input = p_input.ToString();

            String result = "";
            String temp = input;
            String group3number = "";
            String[] ngan = { "", "ngàn ", "triệu ", "tỷ " };
            Byte i = 0;

            // kiểm tra chuổi rỗng
            if (input.Equals(""))
            {
                return "Chưa nhập số tiền.";
            }

            // 65,064
            while (temp.Length > 0)
            {
                // nhóm 3 so
                group3number = Group3Number(temp);
                // doc 3 so
                // sáu mươi lăm (ngàn) không trăm sáu mươi bốn ("")
                //result = Read3Number(group3number) + ngan[i] + result;

                string doc3chuso = Read3Number(group3number);
                result = doc3chuso + (doc3chuso == "" ? "" : ngan[i]) + result;

                // loai bo 3 so tu ben phai wa
                temp = temp.Substring(0, temp.Length - group3number.Length);

                i++;
                if (i > 3)
                {
                    i = 1;
                }
            }
            // doc 3 so
            // ghep chuoi
            //return result + "đồng";
            return result.Substring(0, 1).ToUpper()
                    + result.Substring(1)
                    + "đồng.";
        }

        private static String Group3Number(String input)
        {
            String result = "";
            // 12, 45, 7, 789 ...
            if (input.Length <= 3)
            {
                result = input;
            }
            // 7897, 98908, 980808, ...
            else
            {
                result = input.Substring(input.Length - 3);
            }
            return result;
        }

        private static String Read3Number(String input)
        {
            String result = "";
            if (input.Length == 3)
            {
                result = Read_Tram(input);
            }
            else if (input.Length == 2)
            {
                result = Read_Chuc(input);
            }
            else
            {
                result = Read_Donvi(input);
            }
            return result;
        }

        private static String Read_Donvi(String input)
        {
            String[] donvi = {"không ", "một ", "hai ", "ba ", "bốn ", "năm ",
                        "sáu ", "bảy ", "tám ", "chín "};
            String result = "";
            // 1 số
            if (input.Length == 1)
            {
                Byte num = Byte.Parse(input);
                result += donvi[num];
            }
            return result;
        }

        private static String Read_Chuc(String input)
        {
            String result = "";
            // 2 số
            if (input.Length == 2)
            {
                // 00

                //if (input.charAt(0) == '0' && input.charAt(1) == '0')
                if (input.Substring(0, 1) == "0" && input.Substring(1, 1) == "0")
                {
                    // không đọc
                }
                // 01
                // 10
                // 11
                else
                {
                    // số đầu tiên là 0
                    //if (input.charAt(0) == '0')
                    if (input.Substring(0, 1) == "0")
                    {
                        result += "linh ";
                        result += Read_Donvi(input.Substring(1));
                    }
                    // số đầu tiên là 1
                    //else if (input.charAt(0) == '1')
                    else if (input.Substring(0, 1) == "1")
                    {
                        // mười một, mười hai, ...
                        result += "mười ";
                        //if (input.charAt(1) != '0') // 10 : mười
                        if (input.Substring(1, 1) != "0")
                        {
                            //if (input.charAt(1) == '5') // 15 : mười lăm
                            if (input.Substring(1, 1) == "5")
                            {
                                result += "lăm ";
                            }
                            else
                            {
                                result += Read_Donvi(input.Substring(1));
                            }
                        }
                    }
                    // số đầu tiên là 2, 3, 4, 5, 6, 7, 8, 9
                    else
                    {
                        // hai mươi
                        result += Read_Donvi(input.Substring(0, 1));
                        result += "mươi ";
                        //if (input.charAt(1) != '0') // 20 : hai mươi
                        if (input.Substring(1, 1) != "0")
                        {
                            // hai mươi mốt
                            //if (input.charAt(1) == '1')
                            if (input.Substring(1, 1) == "1")
                            {
                                result += "mốt ";
                            }
                            // hai mươi lăm
                            //else if (input.charAt(1) == '5')
                            else if (input.Substring(1, 1) == "5")
                            {
                                result += "lăm ";
                            }
                            // hai mươi hai, hai mươi ba, ...
                            else
                            {
                                result += Read_Donvi(input.Substring(1));
                            }
                        }
                    }
                }
            }
            return result;
        }

        private static String Read_Tram(String input)
        {
            String result = "";
            // 3 số
            if (input.Length == 3)
            {
                // 000
                //if (input.charAt(0) == '0' && input.charAt(1) == '0' && input.charAt(2) == '0')
                if (input.Substring(0, 1) == "0" && input.Substring(1, 1) == "0"
                    && input.Substring(2, 1) == "0")
                {
                    // không đọc
                }
                // 010
                // 011
                // 100
                // 101
                // 110
                // 111
                else
                {
                    // một trăm
                    result += Read_Donvi(input.Substring(0, 1));
                    result += "trăm ";
                    result += Read_Chuc(input.Substring(1));
                }
            }
            return result;
        }
        #endregion

        #region "Convert numberic to Vietnamese String ver 2"
        public static string ChangeNum2VNStr(this decimal num, string NumberDecimalSeparator)
        {
            string strTemp;
            strTemp = Convert.ToDouble(num).ToString();
            string str_return;
            int daucham = strTemp.IndexOf(".") + strTemp.IndexOf(",") + 1;
            if (daucham > 0)
            {
                string s1 = strTemp.Substring(0, daucham);
                string s2 = (strTemp + "00").Substring(daucham + 1, 2);

                str_return = Num2VNStr(s1) + (NumberDecimalSeparator == "." ? " chấm " : " phẩy ") + Num2VNStr(s2);
            }
            else
            {
                str_return = Num2VNStr(strTemp);
            }
            return str_return.Remove(1).ToUpper() + str_return.Substring(1) + " đồng";
        }

        public static string ChangeNum2VNStr2(this decimal num, string NumberDecimalSeparator = ",")
        {
            string strTemp;
            strTemp = Convert.ToDouble(num).ToString();
            string str_return;
            int daucham = strTemp.IndexOf(".") + strTemp.IndexOf(",") + 1;
            if (daucham > 0)
            {
                string s1 = strTemp.Substring(0, daucham);
                string s2 = (strTemp + "00").Substring(daucham + 1, 2);

                str_return = Num2VNStr(s1) + (NumberDecimalSeparator == "." ? " chấm " : " phẩy ") + Num2VNStr(s2);
            }
            else
            {
                str_return = Num2VNStr(strTemp);
            }
            return str_return.Remove(1).ToUpper() + str_return.Substring(1);
        }

        public static string Num2VNStr(string num)//doc so chan
        {
            string strResult;
            strResult = "";      // Chuoi chua ket qua tra ve

            string[] arrayNumStr = new string[10] 
			{
				"không","một","hai","ba","bốn",
				"năm","sáu","bảy","tám","chín"
			};

            string[] arrayDonVi = new string[4] { "", "ngàn", "triệu", "tỷ" };

            string strDonVi;
            int temp;

            string strTemp;
            strTemp = num;

            int nLen;
            nLen = strTemp.Length;

            int i, vt;
            int a;

            for (i = 0; i < nLen; i++)
            {
                strDonVi = "";
                vt = (nLen - i - 1) % 3;

                a = int.Parse(strTemp.Substring(i, 1));


                switch (a)
                {
                    case 1:
                        if ((vt == 0) && (i > 0))
                        {
                            if ((strTemp.Substring(i - 1, 1) != "1") && (strTemp.Substring(i - 1, 1) != "0"))
                                arrayNumStr[1] = "mốt";
                            else
                                arrayNumStr[1] = "một";
                        }
                        else
                        {
                            if (vt == 1) arrayNumStr[1] = "mười";
                            else arrayNumStr[1] = "một";
                        }
                        break;

                    case 5:
                        if ((vt == 0) && (i != 0))
                        {
                            if (strTemp.Substring(i - 1, 1) != "0")
                                arrayNumStr[5] = "lăm";
                            else
                                arrayNumStr[5] = "năm";
                        }
                        else
                            arrayNumStr[5] = "năm";
                        break;

                    case 0:
                        arrayNumStr[0] = "";
                        if (vt == 1)
                        {
                            if (strTemp.Substring(i + 1, 1) != "0")
                                arrayNumStr[0] = "lẻ";
                        }
                        else if (vt == 2)
                        {
                            if ((strTemp.Substring(i + 1, 1) != "0") || (strTemp.Substring(i + 2, 1) != "0"))
                                arrayNumStr[0] = "không";
                        }
                        else if (vt == 0 && nLen == 1)
                        {
                            arrayNumStr[0] = "không";
                        }
                        break;
                }	// end of switch

                switch (vt)
                {
                    case 2:
                        if (i == 0)
                            strDonVi = "trăm";
                        else if ((strTemp.Substring(i, 1) != "0") ||
                            (strTemp.Substring(i + 1, 1) != "0") ||
                            (strTemp.Substring(i + 2, 1) != "0"))
                            strDonVi = "trăm";
                        break;
                    case 1:
                        if ((strTemp.Substring(i, 1) != "1") && (strTemp.Substring(i, 1) != "0"))
                            strDonVi = "mươi";
                        break;
                    default:
                        temp = (nLen - i) / 3;
                        if (temp > 3) temp = temp % 3;
                        if (i > 2)
                        {
                            if (strTemp.Substring(i - 2, 1) != "0" ||
                                strTemp.Substring(i - 1, 1) != "0" ||
                                strTemp.Substring(i, 1) != "0" ||
                                i == strTemp.Length)
                                strDonVi = arrayDonVi[temp];
                        }
                        else
                            strDonVi = arrayDonVi[temp];
                        break;
                }	// end of switch

                if (arrayNumStr[a] == "")
                    strResult = strResult.Trim() + " " + strDonVi;
                else
                    strResult = strResult.Trim() + " " + arrayNumStr[a] + " " + strDonVi;
            }	// end of for

            return strResult.Trim();
        }
        #endregion

        #endregion


        /// <summary>
        /// Rounds the supplied decimal to the specified amount of decimal points
        /// </summary>
        /// <param name="val">The decimal to round</param>
        /// <param name="decimalPoints">The number of decimal points to round the output value to</param>              
        /// <returns>A rounded decimal</returns>
        public static decimal RoundDecimalPoints(this decimal val, int decimalPoints)
        {
            return Math.Round(val, decimalPoints);
        }

        /// <summary>
        /// Rounds the supplied decimal value to two decimal points
        /// </summary>
        /// <param name="val">The decimal to round</param>
        /// <returns>A decimal value rounded to two decimal points</returns>
        public static decimal RoundToTwoDecimalPoints(this decimal val)
        {
            return Math.Round(val, 2);
        }

        /// <summary>
        /// Returns the absolute value of a System.Decimal number
        /// </summary>
        /// <param name="this"></param>
        /// <returns></returns>
        public static decimal Abs(this decimal @this)
        {
            return Math.Abs(@this);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="this"></param>
        /// <returns></returns>
        public static IEnumerable<decimal> Abs(this IEnumerable<decimal> @this)
        {
            foreach (decimal d in @this)
                yield return d.Abs();
        }
    }
}
