//<auto-generated />

//<auto-generated />

//<auto-generated />

using System;
using System.Collections.Generic;
using System.Diagnostics.Eventing.Reader;
using System.Linq;
using System.Text;
using System.Diagnostics;

namespace CuscLibrary.Log
{
    class WindowLogHelper
    {
        List<EventRecord> GetEventRecords(
            DateTime afterTimestamp,
            DateTime beforeTimestamp,
            LogLevel level,
            string logName,
            string providerName)
        {
            List<EventRecord> eventRecords = new List<EventRecord>();
            EventRecord eventRecord;
            string queryString = String.Format(
                "*[System[(Level = {0}) and Provider[@Name = '{1}']" +
                " and TimeCreated[@SystemTime >= '{2}'] and TimeCreated[@SystemTime <= '{3}']]]",
                (int)level,
                providerName,
                afterTimestamp.ToUniversalTime().ToString("o"),
                beforeTimestamp.ToUniversalTime().ToString("o"));

            EventLogQuery query = new EventLogQuery(logName, PathType.LogName, queryString);
            EventLogReader reader = new EventLogReader(query);
            while ((eventRecord = reader.ReadEvent()) != null)
            {
                eventRecords.Add(eventRecord);
            }

            return eventRecords;
        }

        public enum LogLevel
        {
            Error = 1,
            Information = 2,
        }
    }
}
