//<auto-generated />

#region "Author"
/****************************************************************************************
 * Solution     : CUSC His Framework
 * Project code : APP1105
 * Author       : Dương Nguyễn Phú Cường
 * Company      : Cusc Software
 * Version      : 1.0.0.1
 * Created date : 29/03/2013
 ***************************************************************************************/
#endregion

using System.Net;
using System.Net.Mail;

namespace KFLibrary.Emails
{
    class EmailWrapper
    {
        public void SendEmail(string address, string subject, string message)
        {
            string email = "yrshaikh.mail@gmail.com";
            string password = "put-your-GMAIL-password-here";

            var loginInfo = new NetworkCredential(email, password);
            var msg = new MailMessage();
            var smtpClient = new SmtpClient("smtp.gmail.com", 587);

            msg.From = new MailAddress(email);
            msg.To.Add(new MailAddress(address));
            msg.Subject = subject;
            msg.Body = message;
            msg.IsBodyHtml = true;

            smtpClient.EnableSsl = true;
            smtpClient.UseDefaultCredentials = false;
            smtpClient.Credentials = loginInfo;
            smtpClient.Send(msg);
        }
    }

}


//using System;
//using System.Net;
//using System.Net.Mail;

//namespace SendMailViaGmail
//{
//   class Program
//   {
//   static void Main(string[] args)
//   {

//      //Specify senders gmail address
//      string SendersAddress = "Sendersaddress@gmail.com";
//      //Specify The Address You want to sent Email To(can be any valid email address)
//      string ReceiversAddress = "ReceiversAddress@yahoo.com";
//      //Specify The password of gmial account u are using to sent mail(pw of sender@gmail.com)
//      const string SendersPassword = "Password";
//      //Write the subject of ur mail
//      const string subject = "Testing";
//      //Write the contents of your mail
//      const string body = "Hi This Is my Mail From Gmail";

//      try
//      {
//        //we will use Smtp client which allows us to send email using SMTP Protocol
//        //i have specified the properties of SmtpClient smtp within{}
//        //gmails smtp server name is smtp.gmail.com and port number is 587
//        SmtpClient smtp = new SmtpClient
//        {
//           Host = "smtp.gmail.com",
//           Port = 587,
//           EnableSsl = true,
//           DeliveryMethod = SmtpDeliveryMethod.Network,
//           Credentials = new NetworkCredential(SendersAddress, SendersPassword),
//           Timeout = 3000
//        };

//        //MailMessage represents a mail message
//        //it is 4 parameters(From,TO,subject,body)

//        MailMessage message = new MailMessage(SendersAddress, ReceiversAddress, subject, body);
//        /*WE use smtp sever we specified above to send the message(MailMessage message)*/

//        smtp.Send(message);
//        Console.WriteLine("Message Sent Successfully");
//        Console.ReadKey();
//     }
//     catch (Exception ex)
//     {
//        Console.WriteLine(ex.Message);
//        Console.ReadKey();
//     }
//}
//}
//}




//using System.Net;
//using System.Net.Mail;

//public void email_send()
//{
//    MailMessage mail = new MailMessage();
//    SmtpClient SmtpServer = new SmtpClient("smtp.gmail.com");
//    mail.From = new MailAddress("your mail@gmail.com");
//    mail.To.Add("to_mail@gmail.com");
//    mail.Subject = "Test Mail - 1";
//    mail.Body = "mail with attachment";

//    System.Net.Mail.Attachment attachment;
//    attachment = new System.Net.Mail.Attachment("c:/textfile.txt");
//    mail.Attachments.Add(attachment);

//    SmtpServer.Port = 587;
//    SmtpServer.Credentials = new System.Net.NetworkCredential("your mail@gmail.com", "your password");
//    SmtpServer.EnableSsl = true;

//    SmtpServer.Send(mail);

//}
