//<auto-generated />

#region "Author"
/****************************************************************************************
 * Solution     : CUSC His Framework
 * Project code : APP1105
 * Author       : Dương Nguyễn Phú Cường
 * Company      : Cusc Software
 * Version      : 1.0.0.1
 * Created date : 29/03/2013
 ***************************************************************************************/
#endregion

using System;
using System.Security.Cryptography;
using System.Text;

namespace KFLibrary.Encryptions
{
    public class Encrypt
    {
        /// <summary>
        /// Hàm mã hóa chuỗi theo MD5
        /// </summary>
        /// <param name="strSource">Chuỗi nguồn cần mã hóa</param>
        /// <returns>Chuỗi đã được mã hóa theo MD5</returns>
        public static string MD5_Encode(string strSource)
        {
            // Tạo obj MD5
            MD5 md5 = MD5.Create();
            // Tạo mảng byte được mã hóa theo MD5 từ chuỗi nguồn
            byte[] data = md5.ComputeHash(Encoding.Default.GetBytes(strSource));
            // Tạo đối tượng string builder
            StringBuilder strBuilder = new StringBuilder();
            // Duyệt qua các byte trong mảng data
            for (int i = 0; i < data.Length; i++)
            {
                // Chuyển byte đang xét theo dạng Hex và nối vào string builder 
                strBuilder.Append(data[i].ToString("x2"));
            }
            // Trả về chuỗi dạng Hex
            return strBuilder.ToString();
        }

        /// <summary>
        /// Hàm so sánh chuỗi nguồn với chuỗi đã được mã hóa theo MD5
        /// </summary>
        /// <param name="strSource">Chuỗi nguồn cần so sánh</param>
        /// <param name="hashSource">Chuỗi đã được mã hóa</param>
        /// <returns>Đúng khi chuỗi nguồn bằng với chuỗi đã được mã hóa, và ngược lại</returns>
        public static bool MD5_Verify(string strSource, string hashSource)
        {
            // Tạo chuỗi tạm chứa chuỗi nguồn được mã hóa theo MD5
            string hashTemp = MD5_Encode(strSource);
            // So sánh tham số chuỗi đã được mã hóa theo MD5 với chuỗi tạm
            if (String.Compare(hashTemp, hashSource, true) == 0)
            {
                // Đúng
                return true;
            }
            else
            {
                // Sai
                return false;
            }
        }
    }
}
