//<auto-generated />

#region "Author"
/****************************************************************************************
 * Solution     : CUSC His Framework
 * Project code : APP1105
 * Author       : Dương Nguyễn Phú Cường
 * Company      : Cusc Software
 * Version      : 1.0.0.1
 * Created date : 29/03/2013
 ***************************************************************************************/
#endregion

using DevExpress.XtraEditors;
using DevExpress.XtraEditors.DXErrorProvider;

namespace KFLibrary.Win.WinForm.DevEx.Validations
{
    public static class Validate
    {
        public static void EmptyStringRule(DXErrorProvider errorProvider,
            BaseEdit control,
            string msgError,
            ErrorType errorType = ErrorType.Critical)
        {
            if (control.Text == null || control.Text.Trim().Length == 0)
            {
                errorProvider.SetError(control, msgError, errorType);
            }
            else
            {
                errorProvider.SetError(control, "");
            }
        }

        /*
         * IsNotNull
         * IsEmply
         * Equal
         * Max
         * Min
         * IsEmail
         * IsPhone
         * 
         */
    }
}
