//<auto-generated />

namespace KFLibrary.Win.WinForm.DevEx.Controls
{
    partial class MaBenhNhan
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.layoutControl1 = new DevExpress.XtraLayout.LayoutControl();
            this.txtReadOnly = new DevExpress.XtraEditors.TextEdit();
            this.txt01 = new DevExpress.XtraEditors.TextEdit();
            this.txt02 = new DevExpress.XtraEditors.TextEdit();
            this.txt03 = new DevExpress.XtraEditors.TextEdit();
            this.lcgReadOnly = new DevExpress.XtraLayout.LayoutControlGroup();
            this.lciReadOnly = new DevExpress.XtraLayout.LayoutControlItem();
            this.layoutControlGroup1 = new DevExpress.XtraLayout.LayoutControlGroup();
            this.lcgEditable = new DevExpress.XtraLayout.LayoutControlGroup();
            this.lciText01 = new DevExpress.XtraLayout.LayoutControlItem();
            this.lciText02 = new DevExpress.XtraLayout.LayoutControlItem();
            this.lciText03 = new DevExpress.XtraLayout.LayoutControlItem();
            this.dxErrorProvider1 = new DevExpress.XtraEditors.DXErrorProvider.DXErrorProvider(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.layoutControl1)).BeginInit();
            this.layoutControl1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.txtReadOnly.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt01.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt02.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt03.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.lcgReadOnly)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.lciReadOnly)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.lcgEditable)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.lciText01)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.lciText02)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.lciText03)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dxErrorProvider1)).BeginInit();
            this.SuspendLayout();
            // 
            // layoutControl1
            // 
            this.layoutControl1.AllowCustomizationMenu = false;
            this.layoutControl1.Controls.Add(this.txtReadOnly);
            this.layoutControl1.Controls.Add(this.txt01);
            this.layoutControl1.Controls.Add(this.txt02);
            this.layoutControl1.Controls.Add(this.txt03);
            this.layoutControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.layoutControl1.HiddenItems.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.lcgReadOnly});
            this.layoutControl1.Location = new System.Drawing.Point(0, 0);
            this.layoutControl1.MinimumSize = new System.Drawing.Size(0, 28);
            this.layoutControl1.Name = "layoutControl1";
            this.layoutControl1.OptionsCustomizationForm.DesignTimeCustomizationFormPositionAndSize = new System.Drawing.Rectangle(681, 286, 250, 350);
            this.layoutControl1.OptionsFocus.AllowFocusReadonlyEditors = false;
            this.layoutControl1.Root = this.layoutControlGroup1;
            this.layoutControl1.Size = new System.Drawing.Size(132, 28);
            this.layoutControl1.TabIndex = 0;
            this.layoutControl1.Text = "layoutControl1";
            // 
            // txtReadOnly
            // 
            this.txtReadOnly.EditValue = "";
            this.txtReadOnly.EnterMoveNextControl = true;
            this.txtReadOnly.Location = new System.Drawing.Point(0, 22);
            this.txtReadOnly.Name = "txtReadOnly";
            this.txtReadOnly.Properties.Appearance.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Bold);
            this.txtReadOnly.Properties.Appearance.Options.UseFont = true;
            this.txtReadOnly.Properties.Appearance.Options.UseTextOptions = true;
            this.txtReadOnly.Properties.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
            this.txtReadOnly.Properties.ReadOnly = true;
            this.txtReadOnly.Size = new System.Drawing.Size(132, 22);
            this.txtReadOnly.StyleController = this.layoutControl1;
            this.txtReadOnly.TabIndex = 6;
            // 
            // txt01
            // 
            this.txt01.EditValue = "";
            this.txt01.EnterMoveNextControl = true;
            this.txt01.Location = new System.Drawing.Point(0, 0);
            this.txt01.Name = "txt01";
            this.txt01.Properties.Appearance.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Bold);
            this.txt01.Properties.Appearance.Options.UseFont = true;
            this.txt01.Properties.Appearance.Options.UseTextOptions = true;
            this.txt01.Properties.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
            this.txt01.Properties.Mask.EditMask = "\\d+";
            this.txt01.Properties.Mask.MaskType = DevExpress.XtraEditors.Mask.MaskType.RegEx;
            this.txt01.Properties.MaxLength = 2;
            this.txt01.Properties.NullValuePrompt = "__";
            this.txt01.Properties.NullValuePromptShowForEmptyValue = true;
            this.txt01.Size = new System.Drawing.Size(42, 22);
            this.txt01.StyleController = this.layoutControl1;
            this.txt01.TabIndex = 4;
            this.txt01.TextChanged += new System.EventHandler(this.txt01_TextChanged);
            this.txt01.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txt01_KeyDown);
            this.txt01.PreviewKeyDown += new System.Windows.Forms.PreviewKeyDownEventHandler(this.txt01_PreviewKeyDown);
            // 
            // txt02
            // 
            this.txt02.EditValue = "";
            this.txt02.EnterMoveNextControl = true;
            this.txt02.Location = new System.Drawing.Point(44, 0);
            this.txt02.Name = "txt02";
            this.txt02.Properties.Appearance.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Bold);
            this.txt02.Properties.Appearance.Options.UseFont = true;
            this.txt02.Properties.Appearance.Options.UseTextOptions = true;
            this.txt02.Properties.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
            this.txt02.Properties.Mask.EditMask = "\\d+";
            this.txt02.Properties.Mask.MaskType = DevExpress.XtraEditors.Mask.MaskType.RegEx;
            this.txt02.Properties.MaxLength = 2;
            this.txt02.Properties.NullValuePrompt = "__";
            this.txt02.Properties.NullValuePromptShowForEmptyValue = true;
            this.txt02.Size = new System.Drawing.Size(26, 22);
            this.txt02.StyleController = this.layoutControl1;
            this.txt02.TabIndex = 4;
            this.txt02.TextChanged += new System.EventHandler(this.txt02_TextChanged);
            this.txt02.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txt02_KeyDown);
            // 
            // txt03
            // 
            this.txt03.EditValue = "";
            this.txt03.EnterMoveNextControl = true;
            this.txt03.Location = new System.Drawing.Point(72, 0);
            this.txt03.Name = "txt03";
            this.txt03.Properties.Appearance.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Bold);
            this.txt03.Properties.Appearance.Options.UseFont = true;
            this.txt03.Properties.Appearance.Options.UseTextOptions = true;
            this.txt03.Properties.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
            this.txt03.Properties.Mask.EditMask = "\\d+";
            this.txt03.Properties.Mask.MaskType = DevExpress.XtraEditors.Mask.MaskType.RegEx;
            this.txt03.Properties.MaxLength = 6;
            this.txt03.Properties.NullValuePrompt = "______";
            this.txt03.Properties.NullValuePromptShowForEmptyValue = true;
            this.txt03.Size = new System.Drawing.Size(60, 22);
            this.txt03.StyleController = this.layoutControl1;
            this.txt03.TabIndex = 5;
            this.txt03.EditValueChanged += new System.EventHandler(this.txt03_TextChanged);
            this.txt03.TextChanged += new System.EventHandler(this.txt03_TextChanged);
            this.txt03.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txt03_KeyDown);
            this.txt03.PreviewKeyDown += new System.Windows.Forms.PreviewKeyDownEventHandler(this.PreviewKeyDown);
            // 
            // lcgReadOnly
            // 
            this.lcgReadOnly.CustomizationFormText = "lcgReadOnly";
            this.lcgReadOnly.GroupBordersVisible = false;
            this.lcgReadOnly.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.lciReadOnly});
            this.lcgReadOnly.Location = new System.Drawing.Point(0, 22);
            this.lcgReadOnly.Name = "lcgReadOnly";
            this.lcgReadOnly.Size = new System.Drawing.Size(132, 304);
            this.lcgReadOnly.Text = "lcgReadOnly";
            // 
            // lciReadOnly
            // 
            this.lciReadOnly.Control = this.txtReadOnly;
            this.lciReadOnly.CustomizationFormText = "lciReadOnly";
            this.lciReadOnly.Location = new System.Drawing.Point(0, 0);
            this.lciReadOnly.MaxSize = new System.Drawing.Size(132, 22);
            this.lciReadOnly.MinSize = new System.Drawing.Size(132, 22);
            this.lciReadOnly.Name = "lciReadOnly";
            this.lciReadOnly.Padding = new DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 0);
            this.lciReadOnly.Size = new System.Drawing.Size(132, 304);
            this.lciReadOnly.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.lciReadOnly.Text = "lciReadOnly";
            this.lciReadOnly.TextSize = new System.Drawing.Size(0, 0);
            this.lciReadOnly.TextToControlDistance = 0;
            this.lciReadOnly.TextVisible = false;
            // 
            // layoutControlGroup1
            // 
            this.layoutControlGroup1.CustomizationFormText = "Root";
            this.layoutControlGroup1.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True;
            this.layoutControlGroup1.GroupBordersVisible = false;
            this.layoutControlGroup1.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.lcgEditable});
            this.layoutControlGroup1.Location = new System.Drawing.Point(0, 0);
            this.layoutControlGroup1.Name = "Root";
            this.layoutControlGroup1.Padding = new DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 0);
            this.layoutControlGroup1.Size = new System.Drawing.Size(132, 28);
            this.layoutControlGroup1.Text = "Root";
            this.layoutControlGroup1.TextVisible = false;
            // 
            // lcgEditable
            // 
            this.lcgEditable.CustomizationFormText = "lcgEditable";
            this.lcgEditable.GroupBordersVisible = false;
            this.lcgEditable.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.lciText01,
            this.lciText02,
            this.lciText03});
            this.lcgEditable.Location = new System.Drawing.Point(0, 0);
            this.lcgEditable.Name = "lcgEditable";
            this.lcgEditable.Size = new System.Drawing.Size(132, 28);
            this.lcgEditable.Text = "lcgEditable";
            // 
            // lciText01
            // 
            this.lciText01.Control = this.txt01;
            this.lciText01.CustomizationFormText = "Ô 1";
            this.lciText01.Location = new System.Drawing.Point(0, 0);
            this.lciText01.MaxSize = new System.Drawing.Size(44, 22);
            this.lciText01.MinSize = new System.Drawing.Size(44, 22);
            this.lciText01.Name = "lciText01";
            this.lciText01.Padding = new DevExpress.XtraLayout.Utils.Padding(0, 2, 0, 0);
            this.lciText01.Size = new System.Drawing.Size(44, 28);
            this.lciText01.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.lciText01.Text = "Ô 1";
            this.lciText01.TextSize = new System.Drawing.Size(0, 0);
            this.lciText01.TextToControlDistance = 0;
            this.lciText01.TextVisible = false;
            // 
            // lciText02
            // 
            this.lciText02.Control = this.txt02;
            this.lciText02.CustomizationFormText = "Ô 2";
            this.lciText02.Location = new System.Drawing.Point(44, 0);
            this.lciText02.MaxSize = new System.Drawing.Size(28, 22);
            this.lciText02.MinSize = new System.Drawing.Size(28, 22);
            this.lciText02.Name = "lciText02";
            this.lciText02.Padding = new DevExpress.XtraLayout.Utils.Padding(0, 2, 0, 0);
            this.lciText02.Size = new System.Drawing.Size(28, 28);
            this.lciText02.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.lciText02.Text = "Ô 2";
            this.lciText02.TextSize = new System.Drawing.Size(0, 0);
            this.lciText02.TextToControlDistance = 0;
            this.lciText02.TextVisible = false;
            // 
            // lciText03
            // 
            this.lciText03.Control = this.txt03;
            this.lciText03.CustomizationFormText = "Ô 3";
            this.lciText03.Location = new System.Drawing.Point(72, 0);
            this.lciText03.MaxSize = new System.Drawing.Size(60, 22);
            this.lciText03.MinSize = new System.Drawing.Size(60, 22);
            this.lciText03.Name = "lciText03";
            this.lciText03.Padding = new DevExpress.XtraLayout.Utils.Padding(0, 0, 0, 0);
            this.lciText03.Size = new System.Drawing.Size(60, 28);
            this.lciText03.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.lciText03.Text = "Ô 3";
            this.lciText03.TextSize = new System.Drawing.Size(0, 0);
            this.lciText03.TextToControlDistance = 0;
            this.lciText03.TextVisible = false;
            // 
            // dxErrorProvider1
            // 
            this.dxErrorProvider1.ContainerControl = this;
            // 
            // MaBenhNhan
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.layoutControl1);
            this.Margin = new System.Windows.Forms.Padding(0);
            this.MinimumSize = new System.Drawing.Size(132, 22);
            this.Name = "MaBenhNhan";
            this.Size = new System.Drawing.Size(132, 22);
            ((System.ComponentModel.ISupportInitialize)(this.layoutControl1)).EndInit();
            this.layoutControl1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.txtReadOnly.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt01.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt02.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt03.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.lcgReadOnly)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.lciReadOnly)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.lcgEditable)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.lciText01)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.lciText02)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.lciText03)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dxErrorProvider1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private DevExpress.XtraLayout.LayoutControl layoutControl1;
        private DevExpress.XtraLayout.LayoutControlGroup layoutControlGroup1;
        private DevExpress.XtraEditors.TextEdit txt03;
        private DevExpress.XtraLayout.LayoutControlItem lciText03;
        private DevExpress.XtraEditors.TextEdit txt02;
        private DevExpress.XtraLayout.LayoutControlItem lciText02;
        private DevExpress.XtraEditors.TextEdit txt01;
        private DevExpress.XtraLayout.LayoutControlItem lciText01;
        private DevExpress.XtraEditors.DXErrorProvider.DXErrorProvider dxErrorProvider1;
        private DevExpress.XtraEditors.TextEdit txtReadOnly;
        private DevExpress.XtraLayout.LayoutControlGroup lcgEditable;
        private DevExpress.XtraLayout.LayoutControlGroup lcgReadOnly;
        private DevExpress.XtraLayout.LayoutControlItem lciReadOnly;
    }
}
