//<auto-generated />

using System.ComponentModel;
using System.ComponentModel.Design;

namespace KFLibrary.Win.WinForm.DevEx.Controls
{
    internal class MaBenhNhanDesignerActionList : DesignerActionList
    {
        /* -------------------------------- Enums ------------------------------------ */
        /* --------------------------------------------------------------------------- */

        /* ------------------------------- Variables --------------------------------- */
        private MaBenhNhan _component;
        private DesignerActionUIService _designerActionUISvc = null;
        /* --------------------------------------------------------------------------- */

        /* ------------------------------ Properties --------------------------------- */
        /* --------------------------------------------------------------------------- */

        /* -------------------------------- Methods ---------------------------------- */
        public MaBenhNhanDesignerActionList(IComponent component)
            : base(component)
        {
            _component = component as MaBenhNhan;

            _designerActionUISvc =
                this.GetService(typeof(DesignerActionUIService))
                    as DesignerActionUIService;
        }

        public override DesignerActionItemCollection GetSortedActionItems()
        {
            DesignerActionItemCollection items = new DesignerActionItemCollection();

            // Items
            items.Add(new DesignerActionHeaderItem("Thông tin"));

            return items;
        }
        /* --------------------------------------------------------------------------- */

        /* --------------------------- Event handlers--------------------------------- */
        /* --------------------------------------------------------------------------- */

        /* --------------------------------- Test ------------------------------------ */
        // Method test code
        private void Test()
        {
            // Todo: test code here
        }
        /* --------------------------------------------------------------------------- */
    }
}
