//<auto-generated />

#region "Author"
/****************************************************************************************
 * Solution     : CUSC His Framework
 * Project code : APP1105
 * Author       : Dương Nguyễn Phú Cường
 * Company      : Cusc Software
 * Version      : 1.0.0.1
 * Created date : 29/03/2013
 ***************************************************************************************/
#endregion

using System;

namespace KFLibrary.Systems
{
    public class SystemInfo
    {

        static void Main(string[] args)
        {
            Console.WriteLine("Operating System Detaiils");
            OperatingSystem os = Environment.OSVersion;
            Console.WriteLine("OS Version: " + os.Version.ToString());
            Console.WriteLine("OS Platoform: " + os.Platform.ToString());
            Console.WriteLine("OS SP: " + os.ServicePack.ToString());
            Console.WriteLine("OS Version String: " + os.VersionString.ToString());
            Console.WriteLine();

            // Get Version details
            Version ver = os.Version;
            Console.WriteLine("Major version: " + ver.Major);
            Console.WriteLine("Major Revision: " + ver.MajorRevision);
            Console.WriteLine("Minor version: " + ver.Minor);
            Console.WriteLine("Minor Revision: " + ver.MinorRevision);
            Console.WriteLine("Build: " + ver.Build);

            Console.ReadLine();
        }

        // private void InsertInfo(string Key, ref ListView lst, bool DontInsertNull)
        //{
        //    lst.Items.Clear();

        //    ManagementObjectSearcher searcher = new ManagementObjectSearcher("select * from " + Key);

        //    try
        //    {
        //        foreach (ManagementObject share in searcher.Get())
        //        {

        //            ListViewGroup grp;
        //            try
        //            {
        //                grp = lst.Groups.Add(share["Name"].ToString(), share["Name"].ToString());
        //            }
        //            catch
        //            {
        //                grp = lst.Groups.Add(share.ToString(), share.ToString());
        //            }

        //            if (share.Properties.Count <= 0)
        //            {
        //                MessageBox.Show("No Information Available", "No Info", MessageBoxButtons.OK, MessageBoxIcon.Information);
        //                return;
        //            }

        //            foreach (PropertyData PC in share.Properties)
        //            {

        //                ListViewItem item = new ListViewItem(grp);
        //                if (lst.Items.Count % 2 != 0)
        //                    item.BackColor = Color.White;
        //                else
        //                    item.BackColor = Color.WhiteSmoke;

        //                item.Text = PC.Name;

        //                if (PC.Value != null && PC.Value.ToString() != "")
        //                {
        //                    switch (PC.Value.GetType().ToString())
        //                    {
        //                        case "System.String[]":
        //                            string[] str = (string[])PC.Value;

        //                            string str2 = "";
        //                            foreach (string st in str)
        //                                str2 += st + " ";

        //                            item.SubItems.Add(str2);

        //                            break;
        //                        case "System.UInt16[]":
        //                            ushort[] shortData = (ushort[])PC.Value;


        //                            string tstr2 = "";
        //                            foreach (ushort st in shortData)
        //                                tstr2 += st.ToString() + " ";

        //                            item.SubItems.Add(tstr2);

        //                            break;

        //                        default:
        //                            item.SubItems.Add(PC.Value.ToString());
        //                            break;
        //                    }
        //                }
        //                else
        //                {
        //                    if (!DontInsertNull)
        //                        item.SubItems.Add("No Information available");
        //                    else
        //                        continue;
        //                }
        //                lst.Items.Add(item);
        //            }
        //        }
        //    }


        //    catch (Exception exp)
        //    {
        //        MessageBox.Show("can't get data because of the followeing error \n" + exp.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Information);
        //    }


        //}

      
    }
}
